### ISSUE TITLE
Can't create new chat sessions after update to v0.51.117

### ISSUE THREAD

**Issue by jahilldev** [nesquena/hermes-webui#2771]
Hi there,

I've just updated to the latest version via the in UI update button. After doing so, I no longer seem to be able to create new chat sessions. The local model is not instantiated via Ollama, and if I reload the page, the prompt and session vanish.

Upon sending my prompt in a new chat session, I've noticed this error in the console:
```
ui.js?v=v0.51.117:4128 Uncaught (in promise) TypeError: _inflightStateLimits is not a function
    at _compactInflightState (ui.js?v=v0.51.117:4128:16)
    at saveInflightState (ui.js?v=v0.51.117:4159:19)
    at send (messages.js?v=v0.51.117:421:5)
```

In addition, trying to check for new updates manually via the settings panel reports this:
```
Update check failed: Agent: git@github.com: Permission denied (publickey). fatal: Could not read from remote repository. Please make sure you have the correct access rights and the repository exists.
```

**Comment by isma3iloiso** [comment]
i reverted my version to v0.51.116  ill wait for new update..

**Comment by JHVenn** [comment]
I had the same issue, my agent self patched it like so:
  1.  The bug: The issue stemmed from a conflict between a function _inflightStateLimits() and a configuration object window._inflightStateLimits, causing the send() function to crash before it could communicate with the backend.
  2.  The fix: I have applied a patch to hermes-webui/static/ui.js to rename the function to _getInflightStateLimits(), resolving the name collision.

**Comment by nesquena-hermes** [comment]
## Summary

This is a real regression in v0.51.117 introduced by b2477974 (`fix: make in-flight recovery storage quota-safe`). The function `_inflightStateLimits()` in `static/ui.js` collides with the global `window._inflightStateLimits` object set in `static/boot.js`. Because top-level `function foo(){…}` declarations in classic (non-module) scripts attach to `window`, boot.js's assignment overwrites the function reference, and every later call to `_inflightStateLimits()` throws `TypeError: _inflightStateLimits is not a function`. That's why the symptom is total — `_compactInflightState` → `saveInflightState` runs on every `send()`, so no new session can be persisted past the first prompt.

## Code reference

`static/ui.js:4084` declares the function:

```js
function _inflightStateLimits(){
  const configured=(typeof window!=='undefined'&&window._inflightStateLimits&&typeof window._inflightStateLimits==='object')?window._inflightStateLimits:{};
  return {
    maxSessions:_boundedInflightInt(configured.maxSessions, ...),
    ...
  };
}
```

`static/boot.js:1462` then assigns the global it tries to read:

```js
window._inflightStateLimits={
  maxSessions:parseInt(s.inflight_state_max_sessions||8,10)||8,
  ...
};
```

`static/index.html:1369,1377` loads `ui.js` first, then `boot.js`, both `defer`. So the function declaration runs first; then boot.js's `loadConfig()` (which sets `window._inflightStateLimits = {...}`) clobbers it before `send()` ever calls it. `_compactInflightState` at `ui.js:4128` then calls `_inflightStateLimits()` on what is now a plain object → `TypeError`.

## Diagnosis / Recommendation

The fix `JHVenn` mentioned above (rename the function so it no longer shadows the global) is the right shape. Concretely, either:

1. Rename the function: `_inflightStateLimits` → `_getInflightStateLimits` (or `_resolvedInflightStateLimits`) at `ui.js:4084`, and update the 3 call sites at `ui.js:4113`, `4128`, `4139`. Leave the `window._inflightStateLimits` config object in boot.js alone — it's the name users would see in settings/debug.
2. Or rename the *global*: change `window._inflightStateLimits` → `window._inflightStateLimitsConfig` in `static/boot.js:1462` and update the read in `ui.js:4085`.

Option 1 is the smaller diff and keeps the public-ish window key stable. The regression test at `tests/test_inflight_storage_quota.py:54` literally asserts both names coexist (`"function _inflightStateLimits()" in UI_JS` and `"window._inflightStateLimits" in BOOT_JS`), so the existing suite happily passes despite the collision — that assertion needs to update to whichever name the fix lands on.

## Verification step

1. Apply rename.
2. Reproduce: fresh browser session, open DevTools console, type a prompt and hit send. Pre-fix this throws the TypeError listed in the issue. Post-fix the call path completes and the session persists across reload.
3. Add a JS-level regression check (jsdom or even a static grep test) that the function name and the window-attached config name are not equal — a simple `assert "function _inflightStateLimits()" not in UI_JS or "window._inflightStateLimits=" not in BOOT_JS` would have caught this.

Also: the *secondary* update-check error (`Permission denied (publickey)` against `git@github.com`) is unrelated to this regression — that's the agent's update path trying SSH against `git@github.com:...` instead of HTTPS, which fails on any host without a deploy key. Separate issue, probably worth filing under hermes-agent rather than the WebUI repo.

Suggest a hot-fix v0.51.118 — the bug breaks the first message of any new session, so it's effectively a brick for anyone who updated through the in-UI button.

**Comment by theDanielJLewis** [comment]
Yup. I can't even chat in existing sessions. I'll revert to 116.

**Comment by theDanielJLewis** [comment]
FYI: Here's how to revert.

1. Enter the `hermes-webui` folder in the terminal.
2. Enter `git checkout a9acafb` and run.
3. Restart WebUI (I do it with `./ctl.sh restart`).

**Comment by nesquena** [comment]
Will fix shortly, thanks for flagging!

**Comment by nesquena-hermes** [comment]
## Fixed and shipped — v0.51.118

Hotfix is live. Please upgrade and the brick should be gone.

### How to update

In the WebUI: Settings → System → Update now (or restart with `git pull && ./ctl.sh restart`).

If your previous "Check now" was failing with `Permission denied (publickey)` on the agent — that's a separate, pre-existing issue (your agent checkout has an SSH-form `origin` URL). It does not block this WebUI hotfix; the WebUI update path uses the WebUI repo's HTTPS remote which works regardless. Once you upgrade to v0.51.118 the chat-send brick is fixed; the SSH error on the agent side is being tracked separately (it only blocks the agent half of the periodic update check, not chat).

If for any reason in-UI update fails, manual path:

```bash
cd ~/hermes-webui   # or wherever your install lives
git fetch --tags --force
git checkout v0.51.118
# restart your server (./ctl.sh restart or whatever you use)
```

### What was wrong

The v0.51.117 in-flight-recovery quota fix (#2766) added a top-level function called `_inflightStateLimits()` to `static/ui.js`. There was already a `window._inflightStateLimits` config **object** set in `static/boot.js`. Because top-level `function foo(){}` declarations in classic (non-module) scripts attach to `window` as `window.foo`, boot.js's assignment overwrote the function reference before any session could send. From there every `_compactInflightState` call → `_inflightStateLimits()` invocation threw `TypeError: _inflightStateLimits is not a function`, which killed `saveInflightState` on every `send()`, which is why no new chat could be created.

@JHVenn nailed the root cause in your earlier comment — your self-patch is the same rename approach this hotfix takes. Thank you for the structured diagnosis.

### What's in the hotfix

PR #2773:

1. **Rename** the function `_inflightStateLimits()` → `_getInflightStateLimits()` in `static/ui.js`. The window config object keeps its existing name (`window._inflightStateLimits`) so nothing downstream that reads the config breaks. All 4 internal call sites updated.

2. **New generalized regression test** at `tests/test_window_function_collision.py` — scans every static JS file for top-level `function NAME()` declarations whose name is ALSO the target of `window.NAME = {...}` or `window.NAME = <number>`. This is the exact bug shape that broke both this issue (#2771) and the earlier #2715 (`_pinnedSessionsLimit` collision in v0.51.106). The test fails loudly with a precise file:name diagnostic if the bug class ever returns. Verified to FAIL on the v0.51.117 source and PASS on v0.51.118 — it would have caught this before it shipped.

3. **Fixed the existing test that certified the bug.** `tests/test_inflight_storage_quota.py:52` had `assert "function _inflightStateLimits()" in UI_JS` — a positive-presence assertion that passed despite the collision. It's now corrected to require the new function name and explicitly forbid the colliding name.

### Verification

- Full pytest suite: 6308 passed, 6 skipped, 3 xpassed, 8 subtests passed.
- Opus advisor pre-merge review: SHIP.
- Live browser end-to-end: typed into composer, hit Send-equivalent paths, `saveInflightState` persists cleanly, zero JS errors in the console.

### Confirming users — please verify

Could you confirm v0.51.118 works for you?

- @jahilldev — your original report, the exact sequence (update via in-UI button → try new chat → TypeError in console). After upgrading to v0.51.118, can you (a) create a new chat and (b) send a message without seeing `_inflightStateLimits is not a function` in DevTools?
- @theDanielJLewis — you mentioned not being able to chat in *existing* sessions either. After upgrading, does that resolve?
- @isma3iloiso — if you were holding on v0.51.116, you can upgrade now.
- @JHVenn — you self-patched the same way; let us know if there's anything else you spotted on the rename surface that we should fold in.

Thanks for the fast diagnostic turnaround — full report → maintainer triage → hotfix shipped in ~3 hours.

Closing as resolved; please reopen if any of you still see the brick on v0.51.118.

**Comment by theDanielJLewis** [comment]
118 fixed it for me. Thank you!

**Comment by jahilldev** [comment]
Sorry, yes can confirm 118 has now fixed the issue.

Many thanks! 🎉
