### ISSUE TITLE
[bug]the last docker image fail to list session or memory

### ISSUE THREAD

**Issue by maxinfo337** [nesquena/hermes-webui#1403]
The last docker image can't show session or memory, this is the error:

[hermes-webui] 2026-05-01T12:18:18.338022168Z [webui] {"ts": "2026-05-01T12:18:18Z", "method": "GET", "path": "/health", "status": 200, "ms": 0.3}
[hermes-webui] 2026-05-01T12:18:48.390578414Z [webui] {"ts": "2026-05-01T12:18:48Z", "method": "GET", "path": "/health", "status": 200, "ms": 0.2}
[hermes-webui] 2026-05-01T12:19:16.810323487Z [webui] {"ts": "2026-05-01T12:19:16Z", "method": "GET", "path": "/api/projects", "status": 200, "ms": 0.6}
[hermes-webui] 2026-05-01T12:19:16.812620404Z [webui] ERROR GET /api/sessions
[hermes-webui] 2026-05-01T12:19:16.812630834Z Traceback (most recent call last):
[hermes-webui] 2026-05-01T12:19:16.812632697Z   File "/app/server.py", line 77, in do_GET
[hermes-webui] 2026-05-01T12:19:16.812634080Z     result = handle_get(self, parsed)
[hermes-webui] 2026-05-01T12:19:16.812635252Z              ^^^^^^^^^^^^^^^^^^^^^^^^
[hermes-webui] 2026-05-01T12:19:16.812636525Z   File "/app/api/routes.py", line 1180, in handle_get
[hermes-webui] 2026-05-01T12:19:16.812637827Z     item["title"] = _redact_text(item["title"])
[hermes-webui] 2026-05-01T12:19:16.812638999Z                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[hermes-webui] 2026-05-01T12:19:16.812640242Z   File "/app/api/helpers.py", line 168, in _combined_redact
[hermes-webui] 2026-05-01T12:19:16.812642304Z     return _fallback_redact(redact_sensitive_text(text, force=True))
[hermes-webui] 2026-05-01T12:19:16.812643657Z                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[hermes-webui] 2026-05-01T12:19:16.812644939Z TypeError: redact_sensitive_text() got an unexpected keyword argument 'force'
[hermes-webui] 2026-05-01T12:19:16.812646112Z 
[hermes-webui] 2026-05-01T12:19:16.812649869Z [webui] {"ts": "2026-05-01T12:19:16Z", "method": "GET", "path": "/api/sessions", "status": 500, "ms": 3.4}
[hermes-webui] 2026-05-01T12:19:16.822038279Z [webui] ERROR GET /api/session?session_id=0fdf6307f2f6&messages=0&resolve_model=0
[hermes-webui] 2026-05-01T12:19:16.822053456Z Traceback (most recent call last):
[hermes-webui] 2026-05-01T12:19:16.822054849Z   File "/app/server.py", line 77, in do_GET
[hermes-webui] 2026-05-01T12:19:16.822055881Z     result = handle_get(self, parsed)
[hermes-webui] 2026-05-01T12:19:16.822056652Z              ^^^^^^^^^^^^^^^^^^^^^^^^
[hermes-webui] 2026-05-01T12:19:16.822057373Z   File "/app/api/routes.py", line 1083, in handle_get
[hermes-webui] 2026-05-01T12:19:16.822058275Z     redact = redact_session_data(raw)
[hermes-webui] 2026-05-01T12:19:16.822058996Z              ^^^^^^^^^^^^^^^^^^^^^^^^
[hermes-webui] 2026-05-01T12:19:16.822059708Z   File "/app/api/helpers.py", line 195, in redact_session_data
[hermes-webui] 2026-05-01T12:19:16.822060519Z     result['title'] = _redact_text(result['title'])
[hermes-webui] 2026-05-01T12:19:16.822061331Z                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[hermes-webui] 2026-05-01T12:19:16.822069456Z   File "/app/api/helpers.py", line 168, in _combined_redact
[hermes-webui] 2026-05-01T12:19:16.822070909Z     return _fallback_redact(redact_sensitive_text(text, force=True))
[hermes-webui] 2026-05-01T12:19:16.822072171Z                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[hermes-webui] 2026-05-01T12:19:16.822073434Z TypeError: redact_sensitive_text() got an unexpected keyword argument 'force'
[hermes-webui] 2026-05-01T12:19:16.827117233Z 
[hermes-webui] 2026-05-01T12:19:16.832254375Z [webui] {"ts": "2026-05-01T12:19:16Z", "method": "GET", "path": "/api/session?session_id=0fdf6307f2f6&messages=0&resolve_model=0", "status": 500, "ms": 11.8}
[hermes-webui] 2026-05-01T12:19:16.832702818Z [webui] {"ts": "2026-05-01T12:19:16Z", "method": "GET", "path": "/api/reasoning", "status": 200, "ms": 17.0}
[hermes-webui] 2026-05-01T12:19:16.838092670Z [webui] {"ts": "2026-05-01T12:19:16Z", "method": "GET", "path": "/api/projects", "status": 200, "ms": 0.3}
[hermes-webui] 2026-05-01T12:19:16.839278322Z [webui] ERROR GET /api/sessions
[hermes-webui] 2026-05-01T12:19:16.839283702Z Traceback (most recent call last):
[hermes-webui] 2026-05-01T12:19:16.839285255Z   File "/app/server.py", line 77, in do_GET
[hermes-webui] 2026-05-01T12:19:16.839286898Z     result = handle_get(self, parsed)
[hermes-webui] 2026-05-01T12:19:16.839288080Z              ^^^^^^^^^^^^^^^^^^^^^^^^
[hermes-webui] 2026-05-01T12:19:16.839289253Z   File "/app/api/routes.py", line 1180, in handle_get
[hermes-webui] 2026-05-01T12:19:16.839290575Z     item["title"] = _redact_text(item["title"])
[hermes-webui] 2026-05-01T12:19:16.839291928Z                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[hermes-webui] 2026-05-01T12:19:16.839293250Z   File "/app/api/helpers.py", line 168, in _combined_redact
[hermes-webui] 2026-05-01T12:19:16.839294573Z     return _fallback_redact(redact_sensitive_text(text, force=True))
[hermes-webui] 2026-05-01T12:19:16.839296035Z                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[hermes-webui] 2026-05-01T12:19:16.839297258Z TypeError: redact_sensitive_text() got an unexpected keyword argument 'force'
[hermes-webui] 2026-05-01T12:19:16.839298440Z 
[hermes-webui] 2026-05-01T12:19:16.839300975Z [webui] {"ts": "2026-05-01T12:19:16Z", "method": "GET", "path": "/api/sessions", "status": 500, "ms": 3.0}
[hermes-webui] 2026-05-01T12:19:17.431213754Z [webui] {"ts": "2026-05-01T12:19:17Z", "method": "GET", "path": "/", "status": 200, "ms": 0.7}
[hermes-webui] 2026-05-01T12:19:17.448071357Z [webui] {"ts": "2026-05-01T12:19:17Z", "method": "GET", "path": "/static/style.css", "status": 200, "ms": 0.4}
[hermes-webui] 2026-05-01T12:19:17.449182622Z [webui] {"ts": "2026-05-01T12:19:17Z", "method": "GET", "path": "/static/i18n.js?v=v0.50.253", "status": 200, "ms": 0.4}
[hermes-webui] 2026-05-01T12:19:17.450365508Z [webui] {"ts": "2026-05-01T12:19:17Z", "method": "GET", "path": "/manifest.json", "status": 200, "ms": 0.8}
[hermes-webui] 2026-05-01T12:19:17.450537789Z [webui] {"ts": "2026-05-01T12:19:17Z", "method": "GET", "path": "/static/vendor/smd.min.js", "status": 200, "ms": 1.3}
[hermes-webui] 2026-05-01T12:19:17.455489467Z [webui] {"ts": "2026-05-01T12:19:17Z", "method": "GET", "path": "/static/icons.js?v=v0.50.253", "status": 200, "ms": 0.3}
[hermes-webui] 2026-05-01T12:19:17.456378588Z [webui] {"ts": "2026-05-01T12:19:17Z", "method": "GET", "path": "/static/ui.js?v=v0.50.253", "status": 200, "ms": 0.2}
[hermes-webui] 2026-05-01T12:19:17.459162660Z [webui] {"ts": "2026-05-01T12:19:17Z", "method": "GET", "path": "/static/terminal.js?v=v0.50.253", "status": 200, "ms": 0.5}
[hermes-webui] 2026-05-01T12:19:17.459477925Z [webui] {"ts": "2026-05-01T12:19:17Z", "method": "GET", "path": "/static/workspace.js?v=v0.50.253", "status": 200, "ms": 1.1}
[hermes-webui] 2026-05-01T12:19:17.460178657Z [webui] {"ts": "2026-05-01T12:19:17Z", "method": "GET", "path": "/static/sessions.js?v=v0.50.253", "status": 200, "ms": 0.8}
[hermes-webui] 2026-05-01T12:19:17.460984383Z [webui] {"ts": "2026-05-01T12:19:17Z", "method": "GET", "path": "/static/messages.js?v=v0.50.253", "status": 200, "ms": 0.9}
[hermes-webui] 2026-05-01T12:19:17.461649810Z [webui] {"ts": "2026-05-01T12:19:17Z", "method": "GET", "path": "/static/panels.js?v=v0.50.253", "status": 200, "ms": 0.8}
[hermes-webui] 2026-05-01T12:19:17.461775474Z [webui] {"ts": "2026-05-01T12:19:17Z", "method": "GET", "path": "/static/commands.js?v=v0.50.253", "status": 200, "ms": 1.3}
[hermes-webui] 2026-05-01T12:19:17.462589014Z [webui] {"ts": "2026-05-01T12:19:17Z", "method": "GET", "path": "/static/onboarding.js?v=v0.50.253", "status": 200, "ms": 0.5}
[hermes-webui] 2026-05-01T12:19:17.463373382Z [webui] {"ts": "2026-05-01T12:19:17Z", "method": "GET", "path": "/static/boot.js?v=v0.50.253", "status": 200, "ms": 0.4}
[hermes-webui] 2026-05-01T12:19:17.479245765Z [webui] {"ts": "2026-05-01T12:19:17Z", "method": "GET", "path": "/api/settings", "status": 200, "ms": 0.3}
[hermes-webui] 2026-05-01T12:19:17.483553316Z [webui] {"ts": "2026-05-01T12:19:17Z", "method": "GET", "path": "/static/favicon.ico", "status": 200, "ms": 0.3}
[hermes-webui] 2026-05-01T12:19:17.484376245Z [webui] {"ts": "2026-05-01T12:19:17Z", "method": "GET", "path": "/api/profile/active", "status": 200, "ms": 0.1}
[hermes-webui] 2026-05-01T12:19:17.487532708Z [webui] {"ts": "2026-05-01T12:19:17Z", "method": "GET", "path": "/api/models", "status": 200, "ms": 0.4}
[hermes-webui] 2026-05-01T12:19:17.488015715Z [webui] {"ts": "2026-05-01T12:19:17Z", "method": "GET", "path": "/api/workspaces", "status": 200, "ms": 0.3}
[hermes-webui] 2026-05-01T12:19:17.492250602Z [webui] {"ts": "2026-05-01T12:19:17Z", "method": "GET", "path": "/api/models/live?provider=custom%3Ahastur", "status": 200, "ms": 0.5}
[hermes-webui] 2026-05-01T12:19:17.493358470Z [webui] {"ts": "2026-05-01T12:19:17Z", "method": "GET", "path": "/api/onboarding/status", "status": 200, "ms": 1.3}
[hermes-webui] 2026-05-01T12:19:17.496400240Z [webui] {"ts": "2026-05-01T12:19:17Z", "method": "GET", "path": "/api/projects", "status": 200, "ms": 0.2}
[hermes-webui] 2026-05-01T12:19:17.499368354Z [webui] ERROR GET /api/sessions
[hermes-webui] 2026-05-01T12:19:17.499380666Z Traceback (most recent call last):
[hermes-webui] 2026-05-01T12:19:17.499382569Z   File "/app/server.py", line 77, in do_GET
[hermes-webui] 2026-05-01T12:19:17.499384052Z     result = handle_get(self, parsed)
[hermes-webui] 2026-05-01T12:19:17.499385254Z              ^^^^^^^^^^^^^^^^^^^^^^^^
[hermes-webui] 2026-05-01T12:19:17.499439465Z   File "/app/api/routes.py", line 1180, in handle_get
[hermes-webui] 2026-05-01T12:19:17.499441519Z     item["title"] = _redact_text(item["title"])
[hermes-webui] 2026-05-01T12:19:17.499442811Z                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[hermes-webui] 2026-05-01T12:19:17.499444064Z   File "/app/api/helpers.py", line 168, in _combined_redact
[hermes-webui] 2026-05-01T12:19:17.499445296Z     return _fallback_redact(redact_sensitive_text(text, force=True))
[hermes-webui] 2026-05-01T12:19:17.499446468Z                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[hermes-webui] 2026-05-01T12:19:17.499447681Z TypeError: redact_sensitive_text() got an unexpected keyword argument 'force'
[hermes-webui] 2026-05-01T12:19:17.499448853Z 
[hermes-webui] 2026-05-01T12:19:17.499449935Z [webui] {"ts": "2026-05-01T12:19:17Z", "method": "GET", "path": "/api/sessions", "status": 500, "ms": 3.4}
[hermes-webui] 2026-05-01T12:19:17.517982029Z [webui] {"ts": "2026-05-01T12:19:17Z", "method": "GET", "path": "/api/reasoning", "status": 200, "ms": 15.5}
[hermes-webui] 2026-05-01T12:19:17.519557957Z [webui] ERROR GET /api/session?session_id=0fdf6307f2f6&messages=0&resolve_model=0
[hermes-webui] 2026-05-01T12:19:17.519566331Z Traceback (most recent call last):
[hermes-webui] 2026-05-01T12:19:17.519568175Z   File "/app/server.py", line 77, in do_GET
[hermes-webui] 2026-05-01T12:19:17.519569788Z     result = handle_get(self, parsed)
[hermes-webui] 2026-05-01T12:19:17.519570990Z              ^^^^^^^^^^^^^^^^^^^^^^^^
[hermes-webui] 2026-05-01T12:19:17.519572303Z   File "/app/api/routes.py", line 1083, in handle_get
[hermes-webui] 2026-05-01T12:19:17.519573705Z     redact = redact_session_data(raw)
[hermes-webui] 2026-05-01T12:19:17.519574807Z              ^^^^^^^^^^^^^^^^^^^^^^^^
[hermes-webui] 2026-05-01T12:19:17.519575980Z   File "/app/api/helpers.py", line 195, in redact_session_data
[hermes-webui] 2026-05-01T12:19:17.519577152Z     result['title'] = _redact_text(result['title'])
[hermes-webui] 2026-05-01T12:19:17.519578264Z                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[hermes-webui] 2026-05-01T12:19:17.519579336Z   File "/app/api/helpers.py", line 168, in _combined_redact
[hermes-webui] 2026-05-01T12:19:17.519580498Z     return _fallback_redact(redact_sensitive_text(text, force=True))
[hermes-webui] 2026-05-01T12:19:17.519581640Z                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[hermes-webui] 2026-05-01T12:19:17.519582772Z TypeError: redact_sensitive_text() got an unexpected keyword argument 'force'
[hermes-webui] 2026-05-01T12:19:17.519583914Z 
[hermes-webui] 2026-05-01T12:19:17.519613178Z [webui] {"ts": "2026-05-01T12:19:17Z", "method": "GET", "path": "/api/session?session_id=0fdf6307f2f6&messages=0&resolve_model=0", "status": 500, "ms": 13.5}
[hermes-webui] 2026-05-01T12:19:17.524786950Z [webui] {"ts": "2026-05-01T12:19:17Z", "method": "GET", "path": "/api/projects", "status": 200, "ms": 0.3}
[hermes-webui] 2026-05-01T12:19:17.526931733Z [webui] ERROR GET /api/sessions
[hermes-webui] 2026-05-01T12:19:17.526943315Z Traceback (most recent call last):
[hermes-webui] 2026-05-01T12:19:17.526946341Z   File "/app/server.py", line 77, in do_GET
[hermes-webui] 2026-05-01T12:19:17.526957953Z     result = handle_get(self, parsed)
[hermes-webui] 2026-05-01T12:19:17.526961209Z              ^^^^^^^^^^^^^^^^^^^^^^^^
[hermes-webui] 2026-05-01T12:19:17.526962211Z   File "/app/api/routes.py", line 1180, in handle_get
[hermes-webui] 2026-05-01T12:19:17.526964164Z     item["title"] = _redact_text(item["title"])
[hermes-webui] 2026-05-01T12:19:17.526965877Z                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[hermes-webui] 2026-05-01T12:19:17.526967500Z   File "/app/api/helpers.py", line 168, in _combined_redact
[hermes-webui] 2026-05-01T12:19:17.526969173Z     return _fallback_redact(redact_sensitive_text(text, force=True))
[hermes-webui] 2026-05-01T12:19:17.526970976Z                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[hermes-webui] 2026-05-01T12:19:17.527413208Z TypeError: redact_sensitive_text() got an unexpected keyword argument 'force'
....
[webui] ERROR GET /api/memory
[hermes-webui] 2026-05-01T13:01:28.939739526Z Traceback (most recent call last):
[hermes-webui] 2026-05-01T13:01:28.939741731Z   File "/app/server.py", line 77, in do_GET
[hermes-webui] 2026-05-01T13:01:28.939743284Z     result = handle_get(self, parsed)
[hermes-webui] 2026-05-01T13:01:28.939744456Z              ^^^^^^^^^^^^^^^^^^^^^^^^
[hermes-webui] 2026-05-01T13:01:28.939745578Z   File "/app/api/routes.py", line 1408, in handle_get
[hermes-webui] 2026-05-01T13:01:28.939746830Z     return _handle_memory_read(handler)
[hermes-webui] 2026-05-01T13:01:28.939747952Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[hermes-webui] 2026-05-01T13:01:28.939749014Z   File "/app/api/routes.py", line 3413, in _handle_memory_read
[hermes-webui] 2026-05-01T13:01:28.939750156Z     "memory": _redact_text(memory),
[hermes-webui] 2026-05-01T13:01:28.939751369Z               ^^^^^^^^^^^^^^^^^^^^
[hermes-webui] 2026-05-01T13:01:28.939752491Z   File "/app/api/helpers.py", line 168, in _combined_redact
[hermes-webui] 2026-05-01T13:01:28.939753693Z     return _fallback_redact(redact_sensitive_text(text, force=True))
[hermes-webui] 2026-05-01T13:01:28.939754815Z                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[hermes-webui] 2026-05-01T13:01:28.939755907Z TypeError: redact_sensitive_text() got an unexpected keyword argument 'force'

and here the version of docker:

com.docker.compose.image = sha256:d9eec79845be30bae75a65fcec396d499fff6af6f4538ff91651506c7145aa82

**Comment by maxinfo337** [comment]
there is already a bug report for this you can delete ! ;)

**Comment by nesquena-hermes** [comment]
Confirmed — this is a duplicate of #1394 (same `redact_sensitive_text() got an unexpected keyword argument 'force'` TypeError on `/api/sessions`). The fix is already in PR #1400.

Closing this one is fine; the underlying bug is being tracked there.

**Comment by nesquena-hermes** [comment]
Closing as duplicate of #1394 (same `redact_sensitive_text() got an unexpected keyword argument 'force'` TypeError on `/api/sessions` and `/api/memory` after upgrading to v0.50.252).

The fix is in PR #1400, which adds a `try/except TypeError` fallback in `_combined_redact()` so deployments running an older bundled `hermes-agent` (without the `force` kwarg in `redact_sensitive_text()`) gracefully fall through to the no-kwarg call instead of crashing the whole API surface.

Once #1400 merges and ships in v0.50.254, the workaround of pinning to v0.50.250 should no longer be needed. Tracking there going forward — thanks for the report!
