### PR TITLE
feat(quota): add Z.AI GLM Coding Plan quota status

### PR DESCRIPTION
**Pull request by shameez-struggles-to-commit**
## Thinking Path

Hermes WebUI already has an ambient provider-quota chip and a Providers quota card, but Z.AI GLM Coding Plan credentials currently fall through to generic credential-pool status with no usage windows. Z.AI’s own subscription dashboard uses a read-only monitor endpoint that returns the plan tier, 5-hour percentage, longer-term limits, and reset timestamps.

This change extends the existing quota abstraction rather than adding another UI. It normalizes Z.AI data into the same `account_limits` shape Codex already uses, keeps the 5-hour window first, and fails soft if the undocumented response changes.

## What Changed

- Add Z.AI quota support via `GET https://api.z.ai/api/monitor/usage/quota/limit`.
- Handle Lite responses where token counts are null and `percentage` is authoritative.
- Surface 5-hour, Daily/Weekly/Monthly windows and reset times through the existing quota card/chip.
- Add a peak-window marker for weekdays 14:00–18:00 Asia/Shanghai.
  - Z.AI exposes no billing-rules API, so multiplier values are explicitly documented plan annotations.
  - Overrides: `ZAI_PEAK_MULTIPLIER`, `ZAI_OFFPEAK_MULTIPLIER`, `ZAI_PEAK_TZ`.
- Add `ZAI_API_KEY` as a read-only alias of canonical `GLM_API_KEY`.
- Preserve shared credential aliases when removing keys (`OPENCODE_API_KEY` remains shared by both OpenCode providers).
- Add a profile/home/key-scoped, bounded single-flight cache with identity-checked ownership and epoch-guarded publication after credential invalidation.
- Harden quota-number coercion and hostile/malformed monitor responses.
- Document the operator knobs and unofficial endpoint in `docs/zai-quota.md`.

## Why It Matters

Z.AI Coding Plan users can see the same account-level quota state already available for Codex without opening the Z.AI dashboard. The UI does not guess: transport/auth/parser failures hide the chip and surface an unavailable card instead of showing stale or fabricated values.

## Related Work

- #6506 fixes a separate issue: it scopes the composer/Hermex quota control to the provider selected for the active session.
- This PR is complementary: it teaches `/api/provider/quota?provider=zai` how to obtain and normalize Z.AI quota data. It does not implement or duplicate session-provider scoping.
- The stacked follow-up PR adds multiple configured OAuth subscription cards to Settings → Providers; it contains no backend quota-provider work.

### Automated

- Post-rebase targeted/neighboring battery: **194/194 passed**.
- Independent focused reviewer battery: **263 passed**.
- Diff-scoped Ruff: **0 new violations**.
- `node --check static/ui.js`: clean.
- `git diff --check`: clean.
- Full-suite independent run: **14,895 passed / 3 unrelated failures**. The failures are in untouched files: macOS setgid preservation and two cron subprocess timing tests that pass in isolation.

### Concurrency

- Superseded-owner regression passed 40 consecutive normal runs.
- Passed 25 additional runs under eight CPU-saturating workers.
- Independent reviewer re-traced publish/removal/notification ordering and epoch/identity invariants.

### Live provider validation

Validated on an isolated WebUI instance against an authenticated Z.AI Lite account:

- 5-hour and Monthly windows rendered with reset timestamps.
- `z.ai` alias resolved to canonical display name.
- Invalid key failed soft and recovered after restoration.
- Peak/off-peak status and local next-switch time rendered correctly.

### UI evidence

After — ambient Z.AI quota chip using the existing composer control:

Z.AI quota chip

Before — on current master the same Z.AI provider has no usable account window, so the existing chip remains hidden. No new control or layout is added by this PR.

## Risks / Follow-ups

- The Z.AI monitor endpoint is unofficial and undocumented, although Z.AI’s dashboard uses it and community tools such as CodexBar/zai-status document it. Parsing is defensive and failure is fail-soft.
- Multiplier annotations are plan-document values, not API facts; operators can override them.
- Non-English `settings_desc_quota_chip` translations retain their existing wide-display wording; `en` is the canonical source per `docs/GUIDELINES.md` rule 8 and locale synchronization can follow separately.
- #6506 remains the owner of active-session composer/Hermex provider switching.

## Release Note

Provider quota visibility now supports Z.AI GLM Coding Plans, including the 5-hour window and a peak-rate marker.

## Model Used

AI assistance was used for implementation and review. The change underwent repeated adversarial plan and code reviews across multiple model families, including a three-round DeepSeek V4 Pro review/fix loop that converged to APPROVE, followed by a split-specific DeepSeek APPROVE and a focused post-rebase APPROVE. All findings were fixed or documented, and all reported verification was executed against committed code.

### CODE REVIEW

**Comment by nesquena-hermes** [comment]
## Summary

I read the full nine-file diff at `83bc20848`, the complete 745-line backend regression file, the complete chip harness and operator note, and the credential alias contract in the current Hermes Agent source. The quota parser, fail-soft envelope, cache ownership checks, and strict browser coercion are carefully covered. One credential-contract gap is still blocking: Hermes Agent accepts a third established Z.AI key name, `Z_AI_API_KEY`, but this PR neither reads, removes, nor scrubs it. A valid Agent configuration can therefore run Z.AI chat while this quota endpoint reports `no_key`, and removing the provider key in Settings can leave the Agent credential active.

## Code reference

The WebUI canonical key is `GLM_API_KEY` at `api/providers.py:717`, but the added alias map at `api/providers.py:756-769` contains only:

```python
"zai": ("ZAI_API_KEY",),
```

That tuple drives both lookup and the new removal logic. At `api/providers.py:3348-3359`, key deletion computes `mine` from `_PROVIDER_ENV_VAR_ALIASES` and clears only aliases in that set:

```python
mine = set(_PROVIDER_ENV_VAR_ALIASES.get(provider_id, ()) or ())
shared = set()
for other, aliases in _PROVIDER_ENV_VAR_ALIASES.items():
    if other != provider_id:
        shared.update(aliases or ())
env_updates.update({alias: None for alias in mine - shared})
```

The current Agent contract recognizes `Z_AI_API_KEY` for Z.AI in `hermes_cli/providers.py:107` and `hermes_cli/auth.py:321`. Because WebUI does not include it in `mine`, that supported credential survives the new Settings removal path. The same omission appears in `tests/test_zai_quota_status.py:710-733`, which seeds and checks only `GLM_API_KEY` plus `ZAI_API_KEY`, and in the test-server environment scrub at `tests/conftest.py:981-987`.

## Diagnosis / recommendation

Add `Z_AI_API_KEY` to the Z.AI alias tuple. That makes `_get_provider_api_key()` agree with Agent authentication and automatically brings the alias into the shared-safe deletion algorithm. Update `docs/zai-quota.md` so the accepted key names match the runtime contract rather than presenting only one alias.

## Verification step

Add two focused regressions:

1. with only `Z_AI_API_KEY` configured, `get_provider_quota("zai")` reaches the mocked monitor fetch instead of returning `no_key`;
2. `set_provider_key("zai", None)` removes `GLM_API_KEY`, `ZAI_API_KEY`, and `Z_AI_API_KEY`, while the existing OpenCode shared-alias control still survives.

Also scrub `Z_AI_API_KEY` in `tests/conftest.py` so ambient Agent credentials cannot make quota tests non-hermetic. I did not execute contributor-authored code during this read-only review.

**Comment by shameez-struggles-to-commit** [comment]
Implemented the requested Agent credential-contract alignment in `f2b18339`.

### What changed

- Added `Z_AI_API_KEY` alongside `GLM_API_KEY` and `ZAI_API_KEY` in the Z.AI alias tuple.
- The existing `_get_provider_api_key()` alias path now reads it from `.env` and thread/process environment.
- Settings key removal now clears all three Z.AI names while preserving shared aliases such as `OPENCODE_API_KEY`.
- Added `Z_AI_API_KEY` to the test-server credential scrub.
- Updated `docs/zai-quota.md` to list the full Hermes Agent contract.

### Focused regressions

- Z_AI_API_KEY-only configuration reaches the mocked Z.AI monitor fetch and returns `available` instead of `no_key`.
- `set_provider_key("zai", None)` removes `GLM_API_KEY`, `ZAI_API_KEY`, and `Z_AI_API_KEY`; the existing OpenCode bridge control still proves `OPENCODE_API_KEY` survives sibling-provider removal.

### Verification

- `test_zai_quota_status.py`: **79/79 passed**
- Provider/quota/removal/plugin neighborhood: **166/166 passed**
- PR1 focused battery: **196/196 passed**
- Stacked PR2 after rebase onto this head: **248/248 passed**
- Ruff diff gate: clean; Node/py_compile checks: clean
- Greptile re-review on `f2b18339`: **5/5 — "No blocking failure remains."**

I also took the non-blocking Greptile efficiency suggestion: provider-specific invalidation now returns immediately for non-Z.AI provider IDs, so unrelated credential changes no longer advance the Z.AI epoch or suppress an otherwise cacheable in-flight response. A regression pins epoch/cache preservation for that case.

**Comment by shameez-struggles-to-commit** [comment]
Friendly ping — pushed `f2b1833` a week ago addressing the credential-contract points from your review. Happy to make further changes if anything's still off.

**Comment by nesquena-hermes** [comment]
## 🔬 Gate certification — RED ⛔

**Certified contributor head:** `f2b1833904cf2ac65bc2aab31521e01b0b40c4a5`  
**Pinned master / tested synthetic integration:** `b0f1536f8796f7ad26be3a560622f1d8981a1de2` / `f153bccd6f5a02024015fd753d9a3985a1dc557f`

**Verdict:** do not merge this head. The parser, alias, cache-partition, and happy-path UI work is substantial, but eight reproduced defects remain across five blocker classes. The unofficial-monitor product decision also remains a separate Nathan call after engineering converges.

**Contributor handoff:** @shameez-struggles-to-commit, this needs the bounded credential-request, cache/fallback, and localization rework specified below before a fresh exact-head gate.

### What I ran

- Exact-head threat scan: **CLEAN**, followed only by no-network/no-secrets Layer-3 execution. When the REST diff endpoint later exhausted its quota, I revalidated the unchanged contributor head through Git and used the already-authorized sandbox directly for reviewer-authored probes; no PR code ran bare.
- Rebase-first integration: clean 7-commit synthetic rebase; intended 9-path diff, +1460/-8.
- Codex (`gpt-5.6-sol`, xhigh): **SHIP ONLY WITH FIXES**. I independently reproduced the findings used below.
- Opus 4.8: **GREEN / SAFE** dissent. It treated redirect forwarding and the unbounded read as non-blocking because older quota paths use the same pattern; an existing unsafe precedent does not make the new credential path safe.
- Fable 5.1: **SHIP-WITH-UX-FIXES**. It identified two merge-blocking copy/localization errors.
- Full candidate suite to completion: **15,246 passed, 9 failed, 2 errors, 126 skipped, 1 xfailed, 2 xpassed, 45 subtests passed**.
- Frozen-base control under the identical sandbox/envelope: **15,157 passed, 9 failed, 2 errors, 126 skipped, 1 xfailed, 2 xpassed, 45 subtests passed**. Authenticated comparison: `valid:true`, identical non-pass nodes, zero candidate-only nodes, +89 candidate passes. The 9 failures/2 errors are the shared sandbox topology baseline; neither suite is described as green.
- PR-owned Z.AI quota/parser/cache/chip files: **89 passed**. Locale/i18n structural matrix: **326 passed / 6 skipped**.
- Installed-Agent contract probe: WebUI and Agent agree on `GLM_API_KEY`, `ZAI_API_KEY`, `Z_AI_API_KEY` and the `zai`/`glm`/`z-ai`/`z.ai`/`zhipu` aliases.
- Static gates: `git diff --check`, Node syntax, Ruff-forward, ESLint runtime, and scope-undef all clean.
- Browser/screenshots: not run. The head is already engineering-RED, and the untrusted-PR policy forbids serving contributor JavaScript outside the sandbox. Screenshot deferral is not the failure reason.

### Reproduced blockers

**Eight defects across five blocker classes.**

1. **Credential trust boundary, configured origin ignored.** A Z.AI key configured with `base_url=https://open.bigmodel.cn/api/coding/paas/v4` still goes to the hard-coded `https://api.z.ai/api/monitor/usage/quota/limit`. My production-composed probe captured `configured_origin=open.bigmodel.cn`, `request_origin=api.z.ai`, and the configured bearer on that request. Gate the monitor feature on a verified Coding Plan origin; do not send a regional/general endpoint credential to a different origin. Include the effective monitor origin in cache identity.
2. **Credential trust boundary, redirect forwards the bearer.** `_zai_fetch_quota_payload()` uses the default `urllib.request.urlopen`. The exact stdlib redirect handler preserved `Authorization: Bearer <key>` when the production request was redirected cross-host. Use a no-redirect opener and reject 3xx before any credential can reach another origin.
3. **Resource bound, response body is unbounded.** The production path calls `response.read()` with no size argument. The probe captured `production_read_args=[]`. Read at most a strict cap plus one byte and fail closed on overflow.
4. **Resource bound, failed single-flight fans out.** Five same-key callers made five transport calls after the registered owner failed: one unavailable owner plus four unregistered waiter retries. Waiters must share one terminal failure or elect one bounded replacement owner; a failed flight must not create an N-request burst.
5. **Cache freshness, failed refresh resurrects stale success.** Reproduced sequence: `available → unavailable` on a forced refresh, then the next ordinary request returned the old cached `available`. The flight owner must atomically replace or evict the prior success before signaling waiters; a short-lived sanitized failure cache is acceptable.
6. **Existing-flow fallback regression, Z.AI pool status disappears.** On pinned master, a local Z.AI credential-pool snapshot returns `available` with the pool breakdown. The new unconditional Z.AI branch returns before `_local_pool_snapshot`; with the monitor offline, candidate returned `unavailable`, no pool, and `local_pool_called=false`. Preserve/merge the existing pool breakdown on remote success and fall back to it on no-key, unsupported endpoint, auth, transport, or parser failure.
7. **UX copy/localization, 14 stale locale descriptions.** All 14 non-English `settings_desc_quota_chip` values still describe OpenRouter only and claim the chip appears only at `≥1400px`; no such quota-chip rule exists. Translate the corrected behavior in every maintained locale. Key-count parity does not test meaning.
8. **UX copy, English says hidden when the value relocates.** English says the chip is hidden in burger mode, but the compact composer menu contains and populates a visible `Quota` row. Describe the actual behavior: inline when there is room, relocated into the composer menu in compact mode.

### Required fix

- Close blockers 1–4 in one bounded credentialed-request/single-flight design: effective-origin capability gate, no redirects, strict response cap, bounded deadline/concurrency, and one shared terminal result per flight.
- Close blocker 5 by replacing/evicting stale success atomically on failed forced refresh; add `available → unavailable → unavailable` coverage.
- Close blocker 6 by preserving the existing local-pool envelope and combining it with remote account windows when available.
- Close blockers 7–8 with all-locale copy that matches the actual inline-to-menu relocation.
- Add regressions for each schedule. Preserve the sound alias parity, strict numeric coercion, timezone parsing, profile/home/key cache partition, epoch ownership, and hostile-payload fail-soft behavior already present.

Non-blocking Fable follow-ups for the re-gate: identify the selected window in the tooltip; avoid presenting an env-configurable plan-doc multiplier as an unqualified chip fact; format switch time in the browser's timezone; add an accessible label for the quota control.

### Recommendation to the next agent

**Contributor rework, then full exact-head re-gate.** If engineering becomes green, the visible flow still needs the normal Fable/screenshot approval boundary, and Nathan must decide whether an unofficial reverse-engineered monitor endpoint belongs in core. Do not merge on code quality alone.

**Comment by shameez-struggles-to-commit** [comment]
## Gate-cert rework complete — all 8 blockers closed (heads `5c9fe7bc` → `da5217a4`)

Responding to the RED gate certification. Four commits, each verified by an independent adversarial reviewer (three REJECT→fix rounds before sign-off on the core protocol).

### Blocker 1 — credential trust boundary / configured origin
- Monitor URL is now derived from the provider's **configured origin**: `base_url=https://open.bigmodel.cn/api/coding/paas/v4` → request goes to `open.bigmodel.cn`, never the hard-coded `api.z.ai`. Alias configs (`providers.glm.base_url` etc.) are honored identically.
- Unverifiable origins fail closed **with no request at all**: non-https non-loopback, malformed IPv4 (`127.999.999.999`, `127.0.0.256`), DNS names like `127.evil.example`, userinfo, invalid ports. Loopback is `ipaddress`-parsed (`::1`, `::ffff:127.0.0.1`, `127.0.0.0/8`, `localhost`, `*.localhost`; zone IDs excluded).
- The effective monitor origin is part of the cache key.
- Config-lookup failure distinguishes "nothing configured" (canonical host) from "lookup failed" (fail closed, no request).

### Blocker 2 — redirects
`_ZaiNoRedirectHandler` returns `None` from `redirect_request`; a 3xx surfaces as an explicit `unavailable` with a redirect-specific message. Reviewer probe confirmed: landing request carried **no** Authorization header.

### Blocker 3 — unbounded read
`response.read(_ZAI_QUOTA_MAX_RESPONSE_BYTES + 1)` — 256 KiB cap, fail closed on overflow. `http.client.HTTPException` (truncated chunked responses / `IncompleteRead`) joins the catch tuple.

### Blocker 4 — failed single-flight fan-out
Flights carry **one shared terminal result**. Five same-key callers over a failing owner = **one transport call** (regression-locked). Waiters arriving after a superseded/hung owner elect **one** bounded replacement owner. A JSON `null` body publishes the failure marker like any other failure.

### Blocker 5 — stale-success resurrection
A failed forced refresh **atomically replaces** the cached success with a short-TTL (15 s) sanitized failure marker before signaling waiters. The reproduced sequence `available → unavailable → unavailable` is regression-locked, including the adversarial interleavings: a waiter joined to a superseded flight cannot return the old success after a newer refresh failed; a credential mutation mid-flight invalidates joined results via the epoch guard; the flight publish protocol (cache write, flight removal, supersession conversion, result assignment, waiter signal) is one atomic critical section.

### Blocker 6 — Z.AI pool regression
The pre-existing local credential-pool snapshot is preserved on every failure path (no-key, unusable origin, auth, transport, parser) and **merged** into the account-limits card on remote success (pool envelope + details alongside remote windows + peak).

### Blockers 7/8 — copy/localization
All 15 locale `settings_desc_quota_chip` strings rewritten: no `≥1400px` claim, no "hidden in burger mode" — the copy now says the value relocates into the compact composer menu (which `composerMobileQuotaAction/Label` actually do). A 15-locale copy-shape regression test locks it.

### Non-blocking follow-ups included
Tooltip names the selected window, qualifies plan-doc multipliers (`[plan-doc rate]`), renders switch time in the **browser's** timezone, and the chip carries `aria-label`.

### Evidence
- 46 new/updated regression tests across `tests/test_zai_gate_cert_rework.py` (28), `tests/test_zai_quota_status.py`, `tests/test_zai_quota_chip_js.py` (+5), `tests/test_quota_chip_settings_toggle.py` (15-locale guard)
- Full related battery: **274 passed** (zai/quota/provider/pool/i18n suites) — run via `./scripts/test.sh` per AGENTS.md
- Ruff diff gate vs origin/master: **0 new violations**; `node --check` on ui.js/i18n.js/panels.js: clean
- `docs/zai-quota.md` documents the origin gate, no-redirect, size-cap, failure-marker, and pool-fallback contracts

Note on process: the standing review loop here uses an independent verification subagent per fix round. Rounds 1–2 returned REJECT (5 + 3 findings — all reproduced, all closed with regression tests); round 3 closed all majors and the three remaining minors are in `da5217a4` (unused import, IPv6 scope IDs, dead branch) with the gates green. Requesting a fresh exact-head re-gate at `da5217a4`.

**Review by nesquena-hermes — CHANGES_REQUESTED** [review]
## Re-gate result: one objective concurrency blocker remains

Thanks for the substantial rework. I re-reviewed exact head `da5217a46489af3ad56bd2d69fa93c39cfa7a4a9`. The configured-origin, redirect, response-bound, failure-cache, pool-fallback, parsing, UI-toggle, and locale fixes now hold, and the targeted PR suite passed 170/170 in the no-network/no-secrets sandbox.

The forced-refresh path still breaks the documented same-key single-flight contract. In `api/providers.py`, `_provider_zai_quota_status()` reads the current flight at lines 2619–2620, but `if flight is None or refresh:` registers a new owner for every `refresh=True` caller. Each new owner then reaches `_zai_fetch_quota_payload()` at lines 2658–2661. Four concurrent same-key forced refreshes therefore made four credentialed transport calls, rather than sharing one in-flight request.

I confirmed this with a reviewer-authored, barrier-driven regression run through the sandbox:

```text
FAILED test_concurrent_forced_refreshes_share_one_transport
assert calls["count"] == 1
E assert 4 == 1
```

### Required fix

Preserve `refresh=True` as a completed-cache bypass, but do not let it replace an already-registered same-key flight. A concurrent forced refresh must join the current refresh, so only one transport owner exists for `(canonical provider, profile home, key fingerprint, origin)` at a time. Add a barrier-driven test with several simultaneous `refresh=True` callers that asserts exactly one `_zai_fetch_quota_payload()` call and one shared terminal result.

Please also repair `test_waiter_cannot_return_success_after_newer_refresh_fails` in `tests/test_zai_gate_cert_rework.py`: it starts only one pre-refresh thread, so that thread is the old owner, not a joined waiter. Start distinct old-owner and waiter threads before triggering the newer refresh, otherwise the test duplicates the owner case covered later in the file.

The separate product-curation question about using the unofficial monitor endpoint remains unchanged. It is not a contributor defect; once this concurrency blocker is fixed, the PR returns to that Nathan decision boundary.

**Comment by shameez-struggles-to-commit** [comment]
Forced refresh now joins the in-flight request — `b11f7b10`

## The fix

`if flight is None or refresh:` is now `if flight is None:`. A `refresh=True` caller still bypasses the completed cache (that logic is untouched), but it **joins** any already-registered same-key flight instead of registering its own. Exactly one transport owner exists per `(canonical provider, profile home, key fingerprint, origin)` at a time. The only remaining replacement path is the pre-existing bounded steal: a joiner that waits past the join timeout elects itself replacement owner, gated by the `claimed` flag so at most one stealer exists — the join timeout is now the named constant `_ZAI_QUOTA_JOIN_TIMEOUT_SECONDS` (transport budget + 2 s).

## The requested regression

`test_concurrent_forced_refreshes_share_one_transport` in `tests/test_zai_gate_cert_rework.py`, exactly as specified:

- `threading.Barrier(5)`: four simultaneous `refresh=True` callers + the main-thread releaser.
- Asserts one registered flight, all four callers parked in `.wait()` (frame-checked, not time-guessed) before release.
- Asserts **exactly one** `_zai_fetch_quota_payload()` call — reproduced the review's failure on the parent commit first (`assert 4 == 1`), then green after the fix.
- Asserts one shared terminal result: identical `fetched_at` and `used_percent` across all four responses.

## The repaired test

`test_waiter_cannot_return_success_after_newer_refresh_fails` now starts a **distinct old-owner thread and a distinct waiter thread** (waiter proven parked on the older flight before the refresh fires), then the newer forced refresh joins → times out (patched 0.25 s join timeout) → steals → fails. All three callers — owner, waiter, refresh — assert `unavailable`.

## Consequent test updates

Three prior tests asserted the old supersede-on-refresh behavior this review removes; they are reworked to prove the same invariants through join + bounded steal (`test_forced_refresh_joins_in_flight_older_fetch`, `test_superseded_owner_cannot_evict_newer_flight`, `test_superseded_owner_caller_also_unavailable`). Each was verified to fail on the parent commit before the fix landed. Sequential refresh semantics are unchanged (`test_refresh_bypasses_cache` still green: two back-to-back `refresh=True` calls still make two calls).

## Verification

- Focused 13-suite battery: **282 passed** (incl. all quota/chip/topbar/codex/pool/provider suites).
- Concurrency subset (`forced or waiter or superseded or single_flight or failed_flight`): **5 passed ×5 consecutive runs**, 2.9–3.2 s each.
- Ruff diff gate: **0 findings on added/modified lines**. `node --check` on panels.js/i18n.js: clean.
- Independent adversarial verification of this commit: **APPROVE**, no defects found; all five reworked tests confirmed RED on `da5217a4` in a scratch clone (barrier test `4 == 1`, join test `2 == 1`, steal-path tests fail on the missing constant); both production `refresh=True` call sites (`api/routes.py` passthrough, `panels.js` fetch-once button) re-audited, no caller relies on refresh opening a new flight.

**Review by nesquena-hermes — CHANGES_REQUESTED** [review]
## Re-gate result: immediate fanout fixed, timeout replacement still breaks physical single-flight

Thank you for the focused follow-up. I re-reviewed exact head `b11f7b10d339d60ff6e28fdca14a04d9341e6f29` against the previous `da5217a46489` finding.

The submitted change fixes the named immediate-refresh bug. Concurrent `refresh=True` callers now join the registered same-key flight, and the new barrier regression is mutation-sensitive. The two changed test files pass in the no-network/no-secrets sandbox: **109 passed**.

One objective blocker remains in the bounded-steal path. After a waiter times out, `api/providers.py` marks the old flight claimed, replaces the registry entry with a fresh `_ZaiFlight`, and immediately starts `_zai_fetch_quota_payload()` without waiting for the old physical transport to exit. A second waiter can time out on that replacement and repeat the operation. A sandboxed event-controlled probe held each body open and observed **three concurrent transports for one cache key** after two successive steals. The registry and stale-publication guards remain coherent, but they cap logical owners, not live network bodies. This contradicts the function and operator documentation's one-transport-per-key contract. A waiter can also retain the pre-invalidation key/origin while waiting and start that retired credentialed request after an epoch change; the post-transport epoch check only blocks publication.

### Required fix

- Keep the completed-cache bypass and immediate same-key join.
- Do not start a replacement transport until the prior physical owner has acknowledged exit. Failing soft after the bounded wait is acceptable. If takeover is required, add cancellation/quiescence acknowledgement or a per-key physical transport lock that the old body owns until it returns.
- Re-check the flight epoch and current key/origin after any wait and immediately before the transport side effect, so a pre-invalidation waiter cannot launch a retired credential or origin.
- Add an event-controlled regression with two successive join timeouts. Hold the old bodies open and assert peak same-key transport concurrency stays at one.
- Add an invalidation-before-timeout regression asserting that no later transport receives the old key/origin.

The separate product-curation question about using this monitor endpoint remains unchanged. This review is only for the reproducible concurrency/effect-boundary defect.

**Comment by shameez-struggles-to-commit** [comment]
## Physical single-flight + pre-transport revalidation — `6a51bd01`

Responding to review 5176373527 (bounded-steal path). Both required behaviors and both required regressions are in.

### 1. Replacement transport waits for prior body exit (fail-soft)

Each cache key now has a **per-key physical transport lock** (`_zai_quota_transport_locks`, created under the cache lock). The live request body owns that lock from before `_zai_fetch_quota_payload()` starts until the body returns (released in `finally` before the atomic publish). A replacement owner — the bounded steal, or any later owner — must acquire that lock before starting a transport:

- acquired within `_ZAI_QUOTA_TRANSPORT_WAIT_SECONDS` (transport budget + 2 s) → the prior body has exited; the replacement proceeds (only after the revalidation below);
- not acquired in time → **fail soft**: `unavailable`, no second body started.

The registry/`claimed` logic is unchanged; the lock adds the missing *physical* bound on live network bodies.

### 2. Epoch + live key/origin re-checked immediately before the side effect

After any wait (join timeout, transport-lock wait) and immediately before the request, the owner re-validates under the cache lock:

- `_zai_quota_epoch == epoch_at_start`, and
- the registry entry is still `my_flight`, and
- the **live** key (`_get_provider_api_key("zai")` re-read) and **live** origin (`_zai_configured_origin()` → `_zai_monitor_url()` re-derived) still hash to the same cache key.

Any mismatch → **no request at all** (fail-soft `unavailable`). A waiter that captured the pre-invalidation key/origin can therefore never launch it; the fetch is always issued with the live key/origin or not issued.

### 3. Requested regressions (event-controlled, `tests/test_zai_gate_cert_rework.py`)

- `test_two_successive_steals_keep_peak_transport_concurrency_at_one` — one gated owner, then two successive forced-refresh stealers, each old body held open on its own release event; asserts **peak live same-key transports stays 1** at every point and after drain.
- `test_invalidation_before_timeout_launches_no_retired_credential` — waiter parked on the owner's flight, `invalidate_zai_quota_cache("zai")` fires mid-wait, waiter times out and would steal; asserts **no transport fires after the epoch change**.

### Evidence

| Claim | Method | Result |
|---|---|---|
| Regressions reproduce the reported defect | both tests run against the parent commit `b11f7b10` (pre-fix `api/providers.py`) | **RED**: concurrency test observed "peak live transports hit 3" — the exact three-bodies finding; invalidation test observed a post-invalidation transport firing |
| Regressions pass on the fix | same two tests on `6a51bd01` | **2 passed** (×4 repeat runs, stable) |
| Each guard is necessary | mutation A: bypass only the lock acquire → concurrency regression fails; mutation B: bypass only the pre-transport revalidation → invalidation regression fails | **each mutation killed by exactly its regression** |
| No regression elsewhere | `./scripts/test.sh tests/test_zai_quota_status.py tests/test_zai_quota_chip_js.py tests/test_provider_quota_status.py tests/test_zai_gate_cert_rework.py tests/test_quota_chip_settings_toggle.py` | **173 passed**; 3 full repeats of the two zai suites stable |
| Lint/static gates | `scripts/ruff_lint.py --diff origin/master` (0 findings on added/modified lines); `node --check static/panels.js static/i18n.js` | clean |
| Independent verification | focused adversarial reviewer (DeepSeek) re-ran RED-on-parent, both mutations, the full battery, and the static gates | **APPROVE** — no defects; worktree byte-identical after review |

Docs updated to state the physical contract (`docs/zai-quota.md` + the function docstring). One honest caveat, not in the required scope: `_zai_quota_transport_locks` entries are retained per distinct cache key (an empty `threading.Lock`, ~100 B) and not pruned on credential rotation — bounded by the number of distinct key/origin combos seen, same order as the failure-cache growth; happy to add eviction alongside `_zai_quota_cache_limit()` if wanted.
