### PR TITLE
fix(#5305): nest delegated subagents under gateway-backed WebUI parents

### PR DESCRIPTION
**Pull request by b3nw**
## Thinking Path

I hit this on a gateway-backed deployment: every `delegate_task` child showed up as a
flat top-level **"Subagent Session"** row, and the spawning conversation showed no child
count. Six conversations produced twelve anonymous rows.

My first assumption was that #5244 had regressed, so I checked `state.db` — the lineage
was correct there (`parent_session_id` set, `read_session_lineage_report` returned both
children as `child_session`). That ruled out the agent and the DB and pointed at the
sidebar projection.

Reading `_attachChildSessionsToSidebarRows`, the orphan branch is gated on
`parentIsExternal`, whose `parentSourceMarker` allowlist recognises a WebUI-owned parent
only as `webui`. But with `HERMES_WEBUI_CHAT_BACKEND=gateway` the parent conversation is
mirrored into `state.db` as `source='api_server'`, which `normalize_agent_session_source()`
maps to `session_source='api'`. That marker falls through to "external", so the parent was
misclassified and the child was pushed back out.

That is the residual weakness #5305 itself called out:

> Server still sets `_cross_surface_child_session` for all cross-source pairs; nesting
> depends on client `parentIsExternal` heuristic.

I considered two fixes. Adding `api`/`api_server` to the parent allowlist is the smaller
change, but it keeps the heuristic fragile and still leaves cron/CLI parents broken. I
also tried clearing `_cross_surface_child_session` in `api/agent_sessions.py`, and backed
that out: the flag does double duty, and the no-visible-parent branch relies on it to
suppress delegated children whose parent is filtered out of the current render — removing
it would have traded this bug for that one. So I classified on the child instead, and
added a guard test for the suppression path.

## What Changed

`static/sessions.js` — in `_attachChildSessionsToSidebarRows`, exempt delegated subagent
rows from the cross-surface orphan branch:

```js
-    if(parentRow&&child._cross_surface_child_session&&parentIsExternal){
+    const childSourceMarker=String(child&&(
+      child.raw_source||child.source_tag||child.source
+    )||'').toLowerCase();
+    const childIsDelegatedSubagent=childSourceMarker==='subagent';
+    if(parentRow&&child._cross_surface_child_session&&parentIsExternal&&!childIsDelegatedSubagent){
```

A delegated subagent has no sidebar surface of its own and always belongs under the
conversation that spawned it, whatever surface that parent happens to be recorded under.
`_cross_surface_child_session` is deliberately left set, so the no-visible-parent branch
still suppresses these rows when the parent is out of scope.

No backend change. No change for non-subagent children.

## Why It Matters

Gateway is the chat backend for containerised and multi-profile deployments, so for those
users *all* delegation output landed in the sidebar as anonymous top-level rows, with no
affordance on the parent indicating that it had delegated at all. It is the same pollution
#5244 removed for the direct-backend case.

## Verification

Bound to the shape observed in a live `/api/sessions` payload rather than a fixture
rebuilt from reading the code: `session_source='api'` / `raw_source='api_server'` parent,
`raw_source='subagent'` / `session_source='other'` children carrying
`_cross_surface_child_session: true`.

`./scripts/test.sh` on this branch, via the repo runner's own `.venv` (Python 3.12.3):

```
13666 passed, 193 skipped, 2 xfailed, 1 xpassed, 34 subtests passed in 484.82s
```

Also run green on a Python 3.13 venv (13,631 passed there, where the two
`test_issue2695_packaged_runtime_layout.py` wheel tests skip for lack of `pip` — under the
repo runner they run and pass).

New tests in `tests/test_session_lineage_collapse.py`:

- `test_cross_surface_subagent_child_stacks_under_gateway_api_server_parent` — the repro
  pin. Fails on master (`assert ['gateway_parent','subagent_a','subagent_b'] ==
  ['gateway_parent']`), passes with the fix. Uses the real `_isExternalSession` /
  `_isMessagingSession` / `_isWebUiSourceSession` helpers rather than stubs, so the marker
  path is genuinely exercised.
- `test_delegated_subagent_child_without_visible_parent_stays_suppressed` — guard for the
  #5305 out-of-scope suppression this fix must not regress. Passes both with and without
  the change; it exists to pin the behaviour the implementation deliberately preserves.

Existing coverage that must keep passing and does:
`test_cross_surface_webui_child_session_remains_top_level_when_parent_is_messaging`
(#1802) and `test_archived_hidden_parent_suppresses_cross_surface_child_orphan` (#4293).

Browser behaviour is owned by the browser, so it was checked in a real one — Chromium via
Playwright against a live deployment, rendering the actually-served asset, not an in-page
simulation. Same session data, before and after:

| | sidebar rows | flat "Subagent Session" | child badges |
|---|---|---|---|
| before | 18 | 12 | 0 |
| after | 6 | 0 | 5 |

Expanding the badges nests all 12 children under their 5 parents. Screenshots are ready
to attach to this PR.

Also clean: `npx eslint --no-config-lookup -c eslint.runtime-guard.config.mjs
"static/**/*.js"`, `scripts/scope_undef_gate.py` (18 static files, 3200 project globals,
no undefined references), and `scripts/ruff_lint.py --diff origin/master`.

## Risks / Follow-ups

- **Deliberate widening.** A subagent child of a genuinely messaging/CLI parent now also
  nests instead of orphaning. That matches the intent stated in the function's own comment
  ("delegated subagent rows … should not be forced into orphans"), and such a child has no
  surface of its own to be stranded on — but it is broader than the reported bug and the
  place I would most want a second opinion.
- **Adjacent case left unfixed.** A non-subagent, non-fork `child_session` of a
  gateway-backed parent still hits the same `parentSourceMarker` misclassification.
  Unreached by this repro; `api`/`api_server` arguably belongs in that allowlist as a
  separate change.
- **The flag's double duty is the real debt.** Splitting `_cross_surface_child_session`
  into two signals — "is a surface continuation" versus "follows its parent's scope" —
  would remove the constraint that shaped this fix. Deliberately out of scope.

Release-note wording, if useful:

> **Delegated subagent sessions now nest under their parent conversation on gateway-backed
> WebUI chats (#5305).** With `HERMES_WEBUI_CHAT_BACKEND=gateway` the parent conversation
> is recorded as `api_server` rather than `webui`, which the sidebar's cross-surface check
> read as an external surface — so every `delegate_task` child was promoted to a
> contextless top-level "Subagent Session" row and the parent showed no child count. The
> check now classifies on the child instead of enumerating parent surfaces. Genuine
> cross-surface continuations, and the suppression of delegated children whose parent is
> filtered out of view, are unchanged.

## Model Used

AI-assisted. Provider: Anthropic. Model: Claude Opus 5 (`claude-opus-5`), via Claude Code.

Notable tool use that mattered: diagnosis came from live inspection of a running
deployment over SSH (`state.db` queries, the `/api/sessions` payload, and the served
static asset) rather than from reading the source alone — that is what surfaced
`session_source='api'` as the trigger. The frontend logic was then exercised directly
under Node against the real payload to confirm the projection before and after, and
Playwright drove a real browser for the visual check.

### CODE REVIEW

**Comment by nesquena-hermes** [comment]
## Summary

Reading `static/sessions.js:6883-7072` at head `21ce717f1` against `origin/master`, plus the new and neighboring lineage tests in `tests/test_session_lineage_collapse.py`, the fix is scoped correctly. The WebUI normalization contract maps an `api_server` parent to `session_source=api` at `api/agent_sessions.py:100-101`; the old parent allowlist therefore classified a gateway-backed WebUI conversation as external. Exempting only a child whose raw source is `subagent` repairs that mismatch without changing genuine cross-surface continuation behavior. I found no blocker.

## Code reference

The operative branch at `static/sessions.js:7041-7044` is narrow:

```js
if(parentRow&&child._cross_surface_child_session&&parentIsExternal&&!childIsDelegatedSubagent){
  if(childRenderable) orphans.push({...child,_orphan_child_session:true});
  continue;
}
```

The source marker is derived immediately above from `raw_source`, then `source_tag`, then `source`, matching the normalized sidebar payload. The exemption only matters when a visible parent row exists. The separate no-parent path remains intact at `static/sessions.js:7059-7071`, where a cross-surface child still stays suppressed instead of becoming a contextless top-level row.

## Diagnosis / recommendation

This is the right layer for the reported symptom. The server already exposes both lineage and raw source facts; the bug was in the client projection interpreting `api` as an external parent surface before deciding whether to orphan the child.

The deliberate widening to delegated children of visible messaging or CLI parents is internally consistent: a `subagent` row is execution lineage, not a user-owned continuation surface. Non-subagent children still take the old orphan branch. Existing coverage at `tests/test_session_lineage_collapse.py:728` pins the WebUI-child-under-messaging-parent case, and the archived-parent suppression case remains covered at `tests/test_session_lineage_collapse.py:868`.

Recommendation: ready for maintainer review.

## Verification step

The new gateway-parent regression at `tests/test_session_lineage_collapse.py:502-637` verifies one visible `api_server` parent collapses two delegated children into its child badge. The companion test immediately after it verifies that the same child source remains absent when its parent is outside the visible render. Those tests cover both sides of the flag reuse that made a backend flag-clearing fix unsafe. I reviewed the source and assertions only and did not execute code from the PR worktree.

**Review by nesquena-hermes — CHANGES_REQUESTED** [review]
## 🔬 Gate certification — RED ❌
**Certified head:** `sha:21ce717f155f98dfcb423501cf09bea17a24c5d1` · **PR:** #6510 · _@b3nw, fix(sessions): restore nested subagent hierarchy for gateway-backed chats_
**Verdict:** Fix and re-gate. The hierarchy correction is sound, but exact-head mobile proof found a PR-introduced target-size and keyboard-access regression. The PR is already a direct child of current `origin/master` (`399cd7ab19ce`), so no rebase branch is required.

### What I ran (isolated worktrees, sandboxed candidate execution, leased port 8783)
| Gate | Result |
|------|--------|
| Threat / freshness | CLEAN score 0; live head unchanged; mergeable/clean; all 22 GitHub checks green |
| Codex regression gate | **SAFE TO SHIP**; 111 focused checks plus base-vs-head oracle, no regression found |
| Fable UI/UX gate | **SHIP-UX**, while explicitly noting shared child-disclosure keyboard/tap debt; independent mobile measurement below promotes that debt to a blocker for the newly affected gateway rows |
| Focused + reviewer tests | 103 PR/sibling tests passed; 11-case source-authority/hidden-parent/control matrix passed; the same oracle fails on frozen base as expected |
| Full pytest suite | Sanitized self-contained sandbox clone: **13,723 passed**, 83 skipped, 1 xfailed, 2 xpassed, 34 subtests passed; 4 failures + 2 setup errors were baseline-equivalent in focused base/head attribution, and the serial-only keyless failure passes cleanly in isolation. Not the RED cause. |
| Private/static checks | `node --check` and `git diff --check` passed; private QA 10 passed + one baseline-identical overbroad detector failure in untouched `messages.js`; 11/11 private HTTP sanity checks passed |
| Browser/live drive | Frozen base and exact head compared through real `renderSessionListFromCache()` at desktop 1440×900 and mobile 390×844; native child disclosure was clicked/expanded |

### Findings
- ✅ `static/sessions.js:7037-7041` uses the child’s authoritative source precedence (`raw_source || source_tag || source`) to distinguish a delegated subagent from a genuine cross-surface continuation. Gateway/API, Telegram, and CLI parents therefore keep their delegated children attached to the conversation that launched them.
- ✅ Fail-closed scope behavior remains intact: no-visible-parent and archived/filtered parent trees stay suppressed; non-subagent cross-surface continuations remain top-level.
- ✅ Frozen base reproduced the reported pollution: three unrelated top-level rows, no child badge. Exact head rendered one gateway parent, a visible **2 children** disclosure, and two indented child rows on both desktop and mobile.
- ✅ Child unread/attention state still bubbles to the parent, and the existing search/active-child expansion paths remain unchanged.

### Blocking regression reproduced
- ❌ On frozen base, the two gateway-backed delegated sessions are independent **321×44 px** mobile targets. On this exact head, reaching either child first requires a **68×16 px** disclosure, then presents **282×24 px** child targets. The hierarchy is cleaner, but the new interaction path materially shrinks every child target below the standing 44px mobile floor.
- ❌ The disclosure is a clickable `<span>` at `static/sessions.js:8108-8122`, with no semantic button role, `tabindex`, `aria-expanded`, Enter handler, or Space handler. Keyboard users cannot reveal the newly nested gateway children. The adjacent lineage disclosure already demonstrates the correct keyboard pattern at `static/sessions.js:8079-8105`.
- ❌ CSS confirms there is no larger invisible hit area: `static/style.css:5652-5655` fixes the pill at 16px and child buttons at 3px vertical padding. Cache-cleared real-mobile CDP measurements produced the dimensions above.

### Required fix
1. Make the child disclosure a native button (or equivalent complete button semantics), expose `aria-expanded`, and support native Enter/Space activation.
2. At mobile widths, make the actual disclosure hit target and each `.session-child-session` target at least 44px high. Preserve the compact visual treatment with a transparent hit wrapper/padding if desired; do not make the sidebar visually bulky.
3. Add interaction tests that use native keyboard activation and computed mobile geometry, not direct `.onclick()` calls or CSS source-string assertions.
4. Re-run the same cache-cleared base/head desktop and 390×844 mobile scenarios. The intended result remains one parent + two nested children, with no clipping and no regression to hidden-parent/non-subagent controls.

### Screenshots
Vision-verified before/after desktop and mobile captures were delivered to the maintainer Telegram channel as message IDs `10086`–`10089`:
- frozen base desktop/mobile: 3 top-level rows, 0 nested
- exact head desktop/mobile: 1 top-level row, `2 children`, 2 nested; cache-cleared mobile geometry exposed the blocker above

### Recommendation to the next agent
**Not ready to stage — contributor fix required, then exact-head warm-up and gate re-entry. Preserve @b3nw attribution.**

---
_Gate-certifier layer (warm-up → **gate** → release). I did not merge, tag, deploy, or close anything. This certificate is valid only while the head remains `sha:21ce717f155f98dfcb423501cf09bea17a24c5d1`._

**Comment by b3nw** [comment]
Gate findings addressed in `edade0eb`. Both were real, and the framing was right: nesting made this disclosure the only route to a child row, so its pre-existing debt became load-bearing for exactly the rows this PR affects. My own browser verification checked that nesting *rendered* and never that the control was *reachable* — that is the gap.

## 1. Keyboard access

The disclosure now carries the same semantics as the lineage disclosure 25 lines above it, which already demonstrated the pattern: `role="button"`, `tabindex="0"`, `aria-expanded` tracked in both directions, and Enter/Space via `onkeydown`.

## 2. Mobile touch targets

Measured at 390×844 against the real stylesheet, cache disabled:

| | base | `edade0eb` |
|---|---|---|
| disclosure hit height | 16 px | **44 px** |
| disclosure visual | 68×16 | 68×16 (unchanged) |
| child row target | 282×24 | **369×44** |
| child text clipped | — | no |
| `.session-actions-trigger` | — | reachable |

The hit area is a transparent `::after` spanning only the pill's own width, so the sidebar row does not grow and the visual stays compact, per your "do not make the sidebar visually bulky" constraint. I verified via `elementFromPoint` at the trigger's centre that the enlarged area does not shadow the row's absolutely-positioned `.session-actions` (`z-index:1`).

Scoped to `@media(max-width:700px)`, mirroring the #6350 review-finding-3 precedent already in `style.css`. Desktop keeps its 16 px pill and 24 px rows, pinned by a test asserting the floor does *not* apply there.

## 3. Tests

`tests/test_child_disclosure_accessibility.py` — native key events and computed geometry, no `.onclick()` invocation and no CSS source-string matching.

Worth flagging a correction, because it affects how much the keyboard test is worth: my first version **passed without the fix**. The fixture built the button semantics itself, so it tested the fixture rather than production. It now applies *only* the semantics parsed out of `sessions.js`, so removing `tabindex` makes focus fail and removing the `onkeydown` binding makes the key presses no-ops. On the unfixed tree 3 of the 4 tests fail, including the keyboard one (`disclosure did not accept keyboard focus`); the fourth is the desktop scoping guard, which correctly passes both ways.

## 4. Re-run

`./scripts/test.sh` via the repo runner (Python 3.12.3), `BROWSER` unset:

```
13665 passed, 197 skipped, 2 xfailed, 1 xpassed, 34 subtests passed
```

One failure, and I want to be transparent rather than tidy about it. Across three full runs of this branch I saw three *different* single failures:

- `test_session_lineage_full_transcript` — `AttributeError: 'Handler' object has no attribute '_safe_webui_print'`
- `test_session_cli_scan_fast_path` — same attribute, `'object' object`
- `test_issue5210_http_worker_bound` — `assert 503 == 200`

All three pass in isolation (22/22 together), none is touched by this diff (CSS + JS + tests), and the failure relocates between runs rather than reproducing. The `_safe_webui_print` pair are masked errors: it is called non-defensively on `server.py`'s error-logging paths (389/417) while `routes.py:12354` guards it with `getattr(..., None)`, so a primary exception inside a mock handler surfaces as this attribute error and the real cause never reaches the log. A pristine `origin/master` run through the same runner in a fresh worktree was clean, but that is one sample against your own baseline observation of "4 failures + 2 setup errors ... baseline-equivalent". I did not chase these further since they are outside this change; happy to open a separate issue characterising the masked-exception path if that would be useful.

Also unrelated but found while verifying: `test_gateway_lifecycle_controls.py::test_gateway_start_runs_profile_scoped_agent_cli_and_returns_status` asserts `env["BROWSER"] == "echo"` while `routes.py:1234` uses `env.setdefault`, so it fails on any machine with `BROWSER` already exported. `env -u BROWSER` fixes it. Not an issue in CI.

Ready for re-gate at `edade0eb`. Before/after desktop and mobile captures can be attached on request — `gh` cannot upload images, which is also why the original PR body carries the before/after table rather than screenshots.

**Review by nesquena-hermes — CHANGES_REQUESTED** [review]
## Re-gate result: changes requested

Thanks for the substantive follow-up. The lineage fix remains sound, the basic `role` / `tabindex` / `aria-expanded` / Enter / Space wiring is present, and the child-row height controls now pass. Two objective parts of the accessibility gate are still open at exact head `edade0eba457a6f3822f5ce2a62f54da7e72dd9d`.

### 1. The disclosure is not a 44×44 target for short locales

`static/style.css:5682` gives `.session-child-count::after` a 44px height but leaves `left:0; right:0`, so the hit width remains the pill's content width. The short production Japanese label `2 子` measures **32.4531×44px** at 390×844. Sandboxed Chromium hit tests 21.5px to either side of center both missed the disclosure.

This is the remaining edge of the mobile target-size finding. The long English fixture (`2 children`) masks it.

### 2. The new keyboard test does not execute production disclosure behavior

`tests/test_child_disclosure_accessibility.py:35-50` reduces production to four source-string booleans, then lines 54-89 install a separate fixture-owned toggle. That fixture mutates one stable pill in place. Production instead calls `renderSessionListFromCache()` at `static/sessions.js:8128`, whose `list.innerHTML=''` at line 7601 removes the focused disclosure. An actual Enter expansion therefore loses focus; a subsequent Space key does not collapse it as the new test claims.

The test also measures only pseudo-element height (`__disclosureHitHeight`), not width or the real hit envelope, so all four tests pass while the short-locale target remains 32.45px wide.

### Required fix

1. Keep the compact 16px visual, but make the mobile disclosure's actual centered hit surface at least 44×44 for every locale. Verify the full envelope with `elementFromPoint`, including a short production translation.
2. Exercise the actual production disclosure builder/toggle path in the browser instead of a source-conditioned fixture handler. Preserve or restore focus across expansion/collapse, keep `aria-expanded` synchronized with visible state, and prove native Enter and Space against that real path.
3. Retain the now-green child-row geometry and lineage controls (one parent + nested children, hidden-parent suppression, and non-subagent behavior).

### Exact-head evidence

- Threat scan: CLEAN, score 0
- `tests/test_child_disclosure_accessibility.py`: 4 passed, but false-green for the composition above
- Targeted lineage controls: 5 passed, 50 deselected
- Reviewer short-locale diagnostic through `warmup-safe-test.sh`: measured 32.4531×44px and reproduced both missed side hits

No merge, branch write, or production action was performed.

**Comment by b3nw** [comment]
## Correction — retracting the re-gate request on `edade0eb`

My previous comment reported the mobile disclosure hit height as 44 px. **That number does not hold in the real app.** Please do not re-gate `edade0eb` yet.

I had measured the computed `::after` height in a bare fixture. Re-measuring through the live app at 390×844 with the sidebar drawer actually open, and probing hit-testable points in 1 px steps rather than reading computed style:

```
pill visual height        16 px   (as intended)
computed ::after height   44 px
empirical tappable span   33 px   <-- from -11 px to +21 px around the pill centre
row height                60 px
```

So the overlay reports 44 px but only ~33 px of it actually receives the hit-test — short of the floor requirement 2 sets. The asymmetry is upward: the downward half reaches its full ~22 px, the upward half stops at ~11 px. The near ancestors (`.session-title-row`, `.session-item`, `.session-date-body`, `.session-date-group`) are all `overflow: visible`, and the only `overflow: auto` ancestor (`.session-list`) is 136 px away, so this is something painting above the overlay in the band above the pill rather than a clip. I have not yet pinned which element.

Two things worth recording from this, since both bear on how the fix should be judged:

1. **The transparent-`::after` approach is the wrong shape for this.** It measures well and behaves worse, and its correctness depends on the stacking context around it. A transparent hit *wrapper* — which your requirement 2 explicitly offered as an option — is not subject to that, and is the direction I will take instead.

2. **My test was capable of passing while the app failed.** `tests/test_child_disclosure_accessibility.py` builds the pill in an isolated fixture, so it measured 44 px with no competing siblings. That is precisely the gap your requirement 3 was guarding against, and I did not close it — a computed-geometry assertion in a synthetic DOM is not the same as geometry in the real render path. The replacement test needs to measure the disclosure as rendered by `renderSessionListFromCache()`, not a hand-built replica.

Verified as still correct and unaffected: keyboard access works in the live app — focus lands on `.session-child-count`, `aria-expanded` goes `false -> true`, and Enter alone reveals the two nested children, at both viewports. Child-row targets measure 44 px on mobile and 24 px on desktop through the real render path, so requirement 2's second half holds; it is only the disclosure's own hit area that falls short.

I will push a corrected implementation with a test bound to the real render path, then re-request the gate. Apologies for the premature request.

**Comment by b3nw** [comment]
## Re-gate request on `564cb26f` — both findings addressed

Thanks for the precise re-gate. Both were real. This replaces the `::after`
overlay approach entirely, and the replacement test drives the real render path
rather than a fixture, per requirements 1–3.

### 1. Short-locale target width

The pseudo-element is gone. The disclosure is now a real `<button>` whose own
box is the target, so the label no longer participates in sizing — the short
production label cannot shrink it:

| 390×844, real served app | pre-PR `edade0eb` | `564cb26f` |
|---|---|---|
| control box, label `2 子` | 28.45 × 16 | **44.00 × 44.00** |
| visual pill | 28.45 × 16 | 28.45 × 16 *(unchanged)* |
| `elementFromPoint` resolves to the control | 3 of 9 probed points | **9 of 9** |
| child rows | 44 | 44 |

Probed points are centre, ±15px and ±21px on both axes. `margin-block:-14px`
keeps the 16px row geometry, and the pill is an inner `pointer-events:none`
span so the visual stays compact. `.session-text.has-child-disclosure{overflow:visible}`
lets the box extend past the title row; title ellipsis is unaffected because the
clipping lives on `.session-title`, not `.session-text`, and the sidebar gains no
horizontal scroll (`scrollWidth == clientWidth == 390`). Desktop is untouched
(28.5×16 pill, 24px child rows), scoped by `@media(max-width:700px)`.

### 2. The keyboard test now executes production

`tests/test_child_disclosure_accessibility.py` is rewritten: no source-string
booleans, no fixture-owned toggle. All three tests call the real
`renderSessionListFromCache()` against the real stylesheet, with the short
`2 子` label and a 9-point `elementFromPoint` envelope instead of pseudo-element
height.

You were right that `list.innerHTML=''` destroys the focused disclosure. Native
`<button>` semantics now supply Enter/Space, and focus is explicitly restored to
the rebuilt control by `data-child-key`. Measured through the **real served app**
at 390×844 with the drawer open:

```
Enter  -> children 0->2, aria-expanded false->true, focus retained on .session-child-disclosure
Space  -> children 2->0, aria-expanded true->false, focus retained
```

**Base/head oracle** — the new tests against the unfixed `edade0eb` tree:

```
test_..._clear_mobile_touch_floor   FAILED  assert 28 >= 44
test_..._keeps_focus_across_...     FAILED  assert document.activeElement === el
test_..._keeps_compact_desktop...   PASSED  (desktop scoping guard, passes both ways by design)
```

So both of your findings are reproduced by the tests and fixed by the change.
Note these tests `skip` under `./scripts/test.sh` locally because playwright is
not in the repo `.venv`; I ran them in a dedicated playwright venv (chromium
1228). CI installs playwright and executes them.

### One thing I could not resolve — flagging rather than claiming it clean

Given how the last two rounds went, I would rather hand you an open question than
another number I cannot stand behind.

In my harness, a synthetic click at the control's centre reports `pointerdown` on
`.session-title` instead of the button, while `elementFromPoint` at the *same*
coordinates returns the disclosure, with the rect verified byte-identical
immediately before the click (timers frozen, rAF-stability gated, fresh page per
point). I could not attribute this to the app or to my instrument:

- It reproduces **identically on pre-PR `edade0eb`** and on the `master` base —
  the span behaves the same way — so it is not introduced by this PR.
- Your own gate clicked and expanded this disclosure successfully at both
  viewports, which points at my harness.
- A 60×60 control injected into the same title row *does* receive real clicks,
  proving clicks reach that subtree — but injecting it perturbs the row layout
  (the disclosure shifts to negative x), so it is not a clean control and I am
  not treating it as proof either way.

Requirement 1 asked for `elementFromPoint` verification including a short
translation, which is what the table above reports and what the tests assert. If
you would rather the gate turn on real tap dispatch instead, that measurement is
the piece I have not been able to make trustworthy, and I would want your
harness's reading before I claim it.

Also still absent, not required by the gate but worth recording: the disclosure
has no `aria-controls` pointing at the revealed container, since that container
is appended to `sessionText` rather than the control.

### Not rebased

`564cb26f` is 18 commits behind current `origin/master` (`21bdd7c1`) and shows
`BEHIND`. I left history alone rather than force-push a branch under review,
since the recent staging commits suggest you gate-rebase these yourself. Say the
word if you would prefer it rebased.

**Comment by b3nw** [comment]
### CI note — the red `test` shards are a repo-wide base breakage, not this PR

All 15 `test` shards on `564cb26f` fail with the same unrelated error:

```
tests/test_mcp_server.py ... AttributeError: 'Server' object has no attribute 'list_tools'
mcp_server.py:546:  @server.list_tools()
```

This is an upstream `mcp` package release removing/renaming that decorator — CI
installs it unpinned. It is currently failing **every** branch, not just this one:
`fix/filename-spaces`, `fix/tool-limit-card`, `fix/foreign-msg-limit`,
`feat/sort-project-chips`, `fix/memory-flags`, `fix/worklog-disappear`,
`fix/grok-reasoning-chip`, `fix/loopback-warning` all went red in the same window,
and `fix/tool-limit-card` shows the identical error 300 times across 42
`test_mcp_server.py` failures. This diff touches only `static/sessions.js`,
`static/style.css`, and two sidebar test files.

Everything that does exercise this change is green:

- **`browser-smoke` pass** — boots the real server, loads the pages in headless
  Chromium, zero console errors from the new `<button>` render path
- **`lint` pass**, `changes` pass, `live-to-final` pass
- **All three new a11y tests pass in CI** with playwright actually installed:
  ```
  test_production_disclosure_keeps_focus_across_native_keyboard_toggles  PASSED (3.11 shard 2)
  test_production_disclosure_keeps_compact_desktop_geometry              PASSED (3.11 shard 2)
  test_production_disclosure_and_children_clear_mobile_touch_floor       PASSED (3.11 shard 3)
  ```

Flagging in case the MCP decorator break is worth its own issue and a pin —
happy to open one, but it is outside this PR.

**Review by nesquena-hermes — CHANGES_REQUESTED** [review]
## Deep re-gate: changes still required

I re-gated exact head `564cb26f90f93f11c08a56e5c4069eab0948c0e5` against the two prior accessibility findings. The native button, real-render keyboard path, focus restoration, child-row sizing, and lineage controls are materially better. The targeted sandbox runs passed (`3`, `9`, and `14` tests). One deterministic mobile interaction regression remains, and the geometry oracle still does not close the required production-shell case.

### 1. A disclosure touch also enters the parent row gesture machine

The inner `.session-child-count` now has `pointer-events:none`, so a touchscreen event targets the outer `.session-child-disclosure`. That button stops `pointerdown`, `pointerup`, and `click`, but the session row separately handles `touchstart` and `touchend` at `static/sessions.js:8876-8892`.

`_isSessionActionTarget()` only recognizes the action-menu subtree, and `_finishSessionGesture()` excludes `.session-child-count` but not `.session-child-disclosure`. A disclosure-origin `touchstart` therefore calls `_beginSessionGesture()` and schedules the long-press path. Its `touchend` reaches the parent settlement and schedules `_openSidebarSession()` after 300 ms before the synthetic button click toggles the children. A mobile tap can both expand/collapse and navigate to the parent; a hold can enter the parent long-press path.

Required fix:

- Treat `.session-child-disclosure` as an interactive child target before `_beginSessionGesture()` and again before swipe/long-press/navigation settlement. Prefer one shared target predicate so the pointer and touch paths cannot drift.
- Add a real touch-context regression (`has_touch=True` plus `page.touchscreen.tap`) through `renderSessionListFromCache()`. Wait past 300 ms and assert one disclosure toggle, correct ARIA/focus state, and zero parent opens, menus, or swipes.

### 2. Exercise the 44×44 envelope in the production list composition

The rewritten browser test now executes production rendering, but its DOM has one top-level row and mounts `#sessionList` without the production `.session-list` class. The 44 px button uses `margin-block:-14px`, projecting outside the compact title row, while every `.session-item` has a transform and its own stacking context. The one-row fixture cannot prove the protruding edges remain hit-owned beside a real sibling row or inside the production scrolling shell.

Please mount the production `.session-list` shell, add an adjacent ordinary top-level row, and assert every corner/edge resolves to `.session-child-disclosure`, with no horizontal overflow and the session actions trigger still reachable. Narrow the selector to `.session-child-disclosure` and assert it is a native `button[type=button]`; the current fallback selector can still accept the earlier span shape.

### 3. Keep visible state and `aria-expanded` consistent during search

`aria-expanded` is derived only from `_expandedChildSessionKeys`, while search can force child rows visible independently. Cover search-forced visibility and ensure the button reports the visible state before and after user activation/query clearing.

Threat scan was CLEAN. No PR code ran outside the mandatory sandbox wrapper. I did not merge, push a branch, or touch production.
