### ISSUE TITLE
Desktop: after in-place WebUI upgrade, some already-open tabs lose interactivity (new-session button dead, session switch broken); new tabs/sessions unaffected

### ISSUE THREAD

**Issue by nesquena-hermes** [nesquena/hermes-webui#5428]
## Symptom

After an in-place WebUI update (server upgraded from one build to the next), some **already-open desktop tabs lose interactivity**: the "start new session" button stops responding to clicks and switching between sessions no longer works in those tabs. **Newly opened tabs and newly created sessions are unaffected** — only the older, pre-upgrade tabs end up wedged. Reporter saw 2 of 4 open tabs affected.

_Filed from a Discord community report._

## Platform

Desktop app (wrapper); the web front-end was updated across two adjacent builds. Reporter did not specify OS (Windows/Linux/macOS).

## Suspected area (ambiguous — confirm on triage)

Shape of a **stale-client-after-upgrade** regression: an older tab's webview keeps running the *pre-upgrade* front-end JS against the *freshly upgraded* server. Handlers wired by the old bundle (new-session button, session-switch) break when the server contract or expected globals shifted under them, while fresh tabs load the new bundle and work. Two candidate layers:

1. **WebUI front-end** — the pre-upgrade bundle silently breaks post-upgrade (event handlers throwing, or an API-shape mismatch), leaving the tab partially wedged with no self-heal/reload prompt.
2. **Desktop shell** — the wrapper does not reload/refresh per-tab webviews after detecting an in-place upgrade, so stale tabs are left running old code (cross-tab upgrade coordination gap).

## Dedup done (not a duplicate)

- **#2771** "Can't create new chat sessions after update to v0.51.117" (CLOSED, fixed v0.51.118) — superficially similar (dead new-session button after update) but that was a **specific JS TypeError** (`_inflightStateLimits is not a function`) on the *new* build, fixed by a code patch. This report is *older tabs running the pre-upgrade bundle* on a *current* build — different root cause.
- **#5001** (post-upgrade 401 loop on `/api/profile/active`, CLOSED) and **#4756/#4759** (post-upgrade *cold-cache* stale model list / slow new-tab populate, CLOSED) — this is **not** a whole-app 401 loop and **not** a model-list-only cold-cache: it's *partial per-tab interaction breakage* (dead new-session button + broken session switch) confined to older tabs. Related post-upgrade family, distinct symptom.
- **#5394** (sidebar list stuck after 502 during profile switch, CLOSED) — different trigger (502/profile-switch, not upgrade).

## Repro

1. Have multiple desktop tabs open with active sessions.
2. Apply an in-place WebUI update (server upgraded to the next build).
3. Interact with the already-open (older) tabs: new-session button unresponsive, session switching broken in some of them; newer sessions and newly opened tabs work fine.

## Suggested investigation

- Reproduce by loading a tab on build N, upgrading the server to N+1 without reloading the tab, then clicking new-session / switching sessions — capture the console errors in the stale tab.
- Decide the fix layer: WebUI should detect a version skew (served asset version vs. running bundle) and surface a reload prompt / auto-reload; and/or the desktop shell should refresh its webviews on upgrade. A server-version-vs-client-version banner would cover both the browser and wrapper cases.

**Comment by nesquena-hermes** [comment]
## Summary

The triage in the issue body is right about the shape: this is a stale-client-after-upgrade problem, and the reason it's *partial* (dead new-session button + broken session-switch, but only in the older pre-upgrade tabs) is that WebUI has no general runtime version-skew detection. A tab that loaded bundle N keeps executing N's JS against an N+1 server indefinitely, with no self-heal, until you manually hard-refresh. Newly opened tabs pull the N+1 bundle and work fine — matching exactly what was reported.

## Code reference — why there's no self-heal

Asset versioning exists at the transport layer. Every asset URL carries `?v=__WEBUI_VERSION__` and the service worker cache is keyed by it (`static/sw.js:10`, `static/index.html:29-30, 71, 1697+`):

```js
const CACHE_NAME = 'hermes-shell-__WEBUI_VERSION__';
const VQ = '?v=__WEBUI_VERSION__';
```

But that only helps a *navigation/reload*. It gives the already-running JS no way to notice it's stale. Grepping the static tree, there is no runtime global holding the bundle's own version (no `window.__WEBUI_VERSION__` or equivalent in `boot.js`/`pwa-startup.js`), and no periodic poll that compares a served version against a running one. The only skew-detection anywhere is Kanban-specific and reactive — `_kanbanLooksLikeStaleClientError` in `static/panels.js:2242-2249` catches a 404 from an obsolete Kanban endpoint and renders a "Hard refresh now" button:

```js
function _kanbanLooksLikeStaleClientError(err){
  const msg = String((err && err.message) || err || '').toLowerCase();
  return !!(err && err.status === 404 && (
    msg === 'not found' ||
    msg.includes('unknown kanban endpoint') ||
    msg.includes('stale cached bundle')
  ));
}
```

That's the pattern the app already trusts, but it only fires for one panel. The new-session and session-switch handlers have no equivalent, so when their expected server contract shifts under them post-upgrade, they just fail silently and leave the tab wedged.

## Diagnosis

The layer is the **WebUI front-end**, not the desktop shell. The desktop wrapper's per-tab webviews are just browsers pointed at the same server; a plain browser tab left open across an in-place upgrade would exhibit the same wedge. `settings.webui_version` is already surfaced to the client — `loadSettingsPanel()` reads it at `static/panels.js:8216` (`WebUI: ${settings.webui_version || 'not detected'}`), so the server *already* tells the client its current version. The missing piece is a client that (a) remembers the version it booted with and (b) compares it against the live server version, then prompts a reload on mismatch.

## Recommendation

Generalize the Kanban stale-client pattern into a global guard:

1. At boot, stamp the running bundle version into a JS constant (substitute `__WEBUI_VERSION__` into a `boot.js`/`pwa-startup.js` global the same way `sw.js` already gets it).
2. On an existing signal — the periodic `/api/settings` refresh, or the SSE reconnect path — compare `settings.webui_version` against that boot constant.
3. On mismatch, surface a non-destructive banner ("A new WebUI version is available — reload") wired to the existing `hardRefreshWebUIClient()` at `static/panels.js:2227`, which already unregisters service workers and clears caches before reloading. Reuse it rather than a raw `location.reload()` so the stale SW cache is also cleared.

That covers both the browser and the desktop-wrapper cases with one change, and it's the smallest fix that turns a silent wedge into a one-click recovery. A heavier alternative (auto-reload on skew) risks nuking in-progress composer text, so a banner is the safer default.

## Verification

Reproduce per the issue: load a tab on build N, upgrade the server to N+1 without reloading, then click new-session / switch sessions and capture the console error in the stale tab. The specific thrown error identifies which server-contract change broke the handler (e.g. a renamed endpoint or a changed response shape), which tells you whether an *additional* targeted stale-client catch — like the Kanban one — is also warranted for the session routes in the interim.
