### PR TITLE
fix(#5428): surface stale WebUI client recovery

### LINKED ISSUE #5428: Desktop: after in-place WebUI upgrade, some already-open tabs lose interactivity (new-session button dead, session switch broken); new tabs/sessions unaffected
## Symptom

After an in-place WebUI update (server upgraded from one build to the next), some **already-open desktop tabs lose interactivity**: the "start new session" button stops responding to clicks and switching between sessions no longer works in those tabs. **Newly opened tabs and newly created sessions are unaffected** — only the older, pre-upgrade tabs end up wedged. Reporter saw 2 of 4 open tabs affected.

_Filed from a Discord community report._

## Platform

Desktop app (wrapper); the web front-end was updated across two adjacent builds. Reporter did not specify OS (Windows/Linux/macOS).

## Suspected area (ambiguous — confirm on triage)

Shape of a **stale-client-after-upgrade** regression: an older tab's webview keeps running the *pre-upgrade* front-end JS against the *freshly upgraded* server. Handlers wired by the old bundle (new-session button, session-switch) break when the server contract or expected globals shifted under them, while fresh tabs load the new bundle and work. Two candidate layers:

1. **WebUI front-end** — the pre-upgrade bundle silently breaks post-upgrade (event handlers throwing, or an API-shape mismatch), leaving the tab partially wedged with no self-heal/reload prompt.
2. **Desktop shell** — the wrapper does not reload/refresh per-tab webviews after detecting an in-place upgrade, so stale tabs are left running old code (cross-tab upgrade coordination gap).

## Dedup done (not a duplicate)

- **#2771** "Can't create new chat sessions after update to v0.51.117" (CLOSED, fixed v0.51.118) — superficially similar (dead new-session button after update) but that was a **specific JS TypeError** (`_inflightStateLimits is not a function`) on the *new* build, fixed by a code patch. This report is *older tabs running the pre-upgrade bundle* on a *current* build — different root cause.
- **#5001** (post-upgrade 401 loop on `/api/profile/active`, CLOSED) and **#4756/#4759** (post-upgrade *cold-cache* stale model list / slow new-tab populate, CLOSED) — this is **not** a whole-app 401 loop and **not** a model-list-only cold-cache: it's *partial per-tab interaction breakage* (dead new-session button + broken session switch) confined to older tabs. Related post-upgrade family, distinct symptom.
- **#5394** (sidebar list stuck after 502 during profile switch, CLOSED) — different trigger (502/profile-switch, not upgrade).

## Repro

1. Have multiple desktop tabs open with active sessions.
2. Apply an in-place WebUI update (server upgraded to the next build).
3. Interact with the already-open (older) tabs: new-session button unresponsive, session switching broken in some of them; newer sessions and newly opened tabs work fine.

## Suggested investigation

- Reproduce by loading a tab on build N, upgrading the server to N+1 without reloading the tab, then clicking new-session / switching sessions — capture the console errors in the stale tab.
- Decide the fix layer: WebUI should detect a version skew (served asset version vs. running bundle) and surface a reload prompt / auto-reload; and/or the desktop shell should refresh its webviews on upgrade. A server-version-vs-client-version banner would cover both the browser and wrapper cases.

### PR DESCRIPTION
**Pull request by rodboev**
## Thinking Path

- The issue points to old tabs continuing to run a pre-upgrade WebUI bundle against a newer server, while fresh tabs load the updated assets and work.
- The app already versions static assets and exposes `settings.webui_version`, but already-running tabs never compare their boot bundle version with the live server version.
- This adds a browser-side skew guard that surfaces a hard-refresh recovery banner instead of leaving stale tabs silently wedged.

## What Changed

- `static/index.html`: stamps the running WebUI bundle version and adds a stale-client recovery banner near the existing update banner.
- `static/panels.js`: adds the shared version-skew checker, banner wiring, visible-tab detection, and hard-refresh action reuse.
- `static/boot.js`: checks the boot `/api/settings` response for a version mismatch.
- `tests/test_5428_stale_client_recovery.py`: covers the source wiring and executes the browser helper against mismatch, monitor failure, and negative-space cases.

## Why It Matters

After an in-place upgrade, old tabs now get a visible recovery path as soon as the app can prove they are running a stale bundle. The fix keeps normal interactions intact and lets the user choose the hard refresh, which avoids silently discarding in-progress work.

## Verification

- `pytest tests/test_5428_stale_client_recovery.py -v`
- `pytest tests/test_5428_stale_client_recovery.py tests/test_kanban_ui_static.py::test_kanban_task_detail_renderer_executes_with_log_and_formats_feedback -v`
- `npx eslint --no-config-lookup -c eslint.runtime-guard.config.mjs static/panels.js static/boot.js`

Full-suite CI context, not a required local check: `pytest tests/ -v --timeout=60`.

## Upstream

Closes #5428.

## Model Used

GPT 5.5 via Codex CLI

### CODE REVIEW

File: static/panels.js [hunk 1]
```diff
@@ -2240,6 +2240,73 @@ async function hardRefreshWebUIClient(){
...
+    return _normalizeWebUIVersion(s);
+  }catch(_){ return ''; }
+}
+
+function _showStaleWebUIClientBanner(clientVersion,serverVersion){
+  const banner=document.getElementById('staleClientBanner');
+  if(!banner) return;
+  const msg=document.getElementById('staleClientMessage');
+  const versions=document.getElementById('staleClientVersions');
+  if(msg) msg.textContent='This tab is running an older WebUI version. Hard refresh to restore full functionality.';
```
[the remark this answers is not in the document]
Comment (rodboev) [reply static/panels.js]: Fixed in f3293802. The stale-client banner now says the tab is running a different WebUI version, which is accurate for both upgrades and rollbacks.

File: tests/test_5428_stale_client_recovery.py [hunk 2]
```diff
@@ -0,0 +1,215 @@
...
+    """client=v1, server=v2 reveals staleClientBanner and writes both versions."""
+    helpers = _extract_skew_helpers(PANELS_JS.read_text(encoding="utf-8"))
+    result = _run_harness(
+        _make_stub("v1"),
+        helpers,
+        'checkWebUIVersionSkew({ webui_version: "v2" });',
+    )
+    assert result["display"] == "flex", f"Banner not shown on mismatch: {result}"
+    assert "v1" in result["versions"] and "v2" in result["versions"], (
+        f"Version text missing client+server: {result['versions']!r}"
```
[the remark this answers is not in the document]
Comment (rodboev) [reply tests/test_5428_stale_client_recovery.py:150]: Fixed in f3293802. The Node-backed harness now checks `shutil.which("node")` and skips with a clear pytest reason when Node.js is unavailable.

**Comment by nesquena-hermes** [comment]
## 🔬 Gate certification — GREEN (engineering) ✅ · ⏸️ visible banner → Nathan visual/UX sign-off

**Certified head:** `sha:7d4255d8` (clean rebase, branch `gate-rebase/5480-stale-client-recovery`) · **PR:** #5480 · _rodboev, fix(#5428): surface stale WebUI client recovery_
**Verdict:** Engineering-clean version-skew recovery affordance — stamps the bundle version, compares client vs server, and shows a "hard refresh" banner ONLY on a genuine mismatch (well-guarded against false-fire, no XSS). Codex SAFE, suite green. It adds a visible chat banner → Nathan's visual/UX call.

### What I ran (rebased worktree `/tmp/wt-rebase-5480`)
| Gate | Result |
|------|--------|
| Rebase onto current master | ✅ `git apply` clean |
| Codex (reproduce) | **SAFE TO SHIP** — gated the rebased worktree, 0 findings |
| Full pytest suite | 2 failed / 11865 passed — both non-defects (nous env flake + `test_issue4536` isolation flake) |
| PR's own test | ✅ 10/10 (`test_5428_stale_client_recovery.py`) |

### Findings
**✅ Well-guarded, no false-fire, no XSS:** `checkWebUIVersionSkew(settings)` reads the client bundle version (`window.__HERMES_WEBUI_BUNDLE_VERSION__`, normalized) and `settings.webui_version`, and shows `#staleClientBanner` ONLY when `if(!client||!server) return; if(client===server) return;` both pass — so an unstamped/dev build (`__WEBUI_VERSION__`/`'not detected'` → normalized to `''`) or matching versions never fire the banner; all wrapped in try/catch. The banner text is set via `textContent` (msg + `Running: X → Server: Y`), not innerHTML — no XSS from the version strings. Codex SAFE (0 findings), 10/10 tests.

### Recommendation to the next agent
**Engineering-GREEN — merge from branch `gate-rebase/5480-stale-client-recovery` (`sha:7d4255d8`), NOT the PR's stale head `f3293802` — but PARK for Nathan's visual/UX sign-off (new visible chat banner).** The mechanism is solid (fires only on genuine version skew, false-fire-guarded, textContent-safe, test-covered). The open question is Nathan's call on the banner's look/copy/placement/dismissibility — screenshot it (skew state) for his approval per the visible-surface gate. Useful #5428 recovery (a stale tab after a deploy gets a clear "hard refresh" prompt instead of silent breakage). concept 4/5. Author @rodboev (T1). crit=3. (Screenshot the banner in a forced-skew state before recommending merge.)

---
_Gate-certifier layer (warm-up → **gate** → release). I do not merge/tag/deploy. Rebased onto current master; version-skew false-fire guards (both-present + not-equal + placeholder-normalize) + textContent-no-XSS verified, Codex SAFE + 10/10 + suite green bar 2 known flakes. Engineering green; visible banner → Nathan visual sign-off. Cert valid for sha:7d4255d8._

**Comment by nesquena-hermes** [comment]
Shipped in **v0.51.846** — thanks @rodboev! 🎉

Fixes #5428: an old tab left open across an in-place upgrade now detects the client↔server version skew and surfaces a "hard refresh" recovery banner, instead of silently wedging (dead new-session button / broken session switch).

Nathan approved the banner visually, and it went through the full gate. The gate caught one real false-fire: `_normalizeWebUIVersion()` didn't suppress `unknown` (which `api/updates.py` emits on a git-describe failure in Docker/CI images), so a real client version would have falsely fired the banner against `server=unknown`. Fixed on the release branch (suppress `unknown` + all sentinels case-insensitively) with a regression test. Final gate: Codex SAFE, Opus ship-safe, full suite green (2 unrelated pre-existing env flakes). Credited via `Co-authored-by`.
